### ISSUE TITLE
Scala on Android with Proguard

### ISSUE THREAD

**Issue by longliveenduro** [FasterXML/jackson-module-scala#146]
Definitely not a jackson scala bug, but I cannot get Jackson to work on Android with Scala 2.11 (Jackson 2.4.0-rc1).

Trying to deserialize gives me always:

```
05-09 13:04:26.438    8994-9097/net.gutefrage.android W/System.err﹕ Caused by: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class net.gutefrage.android.rest.client.LoginResponse]: can not instantiate from JSON object (need to add/enable type information?)
05-09 13:04:26.438    8994-9097/net.gutefrage.android W/System.err﹕ at [Source: {"user_id":1,"access_token":"xyz"}; line: 1, column: 2]
05-09 13:04:26.438    8994-9097/net.gutefrage.android W/System.err﹕ at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1065)
05-09 13:04:26.438    8994-9097/net.gutefrage.android W/System.err﹕ at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:268)
05-09 13:04:26.438    8994-9097/net.gutefrage.android W/System.err﹕ at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
05-09 13:04:26.438    8994-9097/net.gutefrage.android W/System.err﹕ at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3053)
05-09 13:04:26.438    8994-9097/net.gutefrage.android W/System.err﹕ at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2148)
05-09 13:04:26.438    8994-9097/net.gutefrage.android W/System.err﹕ at net.gutefrage.android.rest.template.ScalaJacksonHttpMessageConverter.readInternal(ScalaJacksonHttpMessageConverter.scala:74)
```

Proguard is used (mandatory with Scala) and I kept adding a lot of scala libs and jackson to the "keep" options of proguard, but still I get the above exception for a simple case class LoginResponse(id: Int, accessToken: String).

This is my current (huge) proguard config, but still not working:

```
proguardOptions in Android ++= Seq(
  "-keepattributes *Annotation*",
  "-dontobfuscate",
  "-dontpreverify",
  "-repackageclasses ''",
  "-allowaccessmodification",
  "-keep class com.fasterxml.jackson.** { *; }",
  "-keep class scala.** { *; }",
  "-keep class com.google.common.** { *; }",
  "-keep public class scala.Either",
  "-keep public class scala.Function1",
  "-keep public class scala.Function2",
  "-keep public class scala.Tuple2",
  "-keep public class scala.collection.Iterable",
  "-keep public class scala.PartialFunction",
  "-keep public class scala.collection.Seq",
  "-keep public class scala.collection.TraversableOnce",
  "-keep public class scala.collection.generic.CanBuildFrom",
  "-keep public class scala.collection.immutable.Map",
  "-keep public class scala.collection.immutable.List",
  "-keep public class scala.collection.mutable.StringBuilder",
  "-keep public class scala.Predef$$less$colon$less",
  "-keep public class scala.math.Numeric",
  "-keep public class scala.math.Ordering",
  "-keep public class scala.reflect.ClassManifest",
  "-keep public class scala.runtime.IntRef",
  "-keep public class scala.runtime.BooleanRef",
  "-keep public class scala.runtime.AbstractFunction1",
  "-keep public class scala.reflect.Manifest",
  "-keep public class scala.collection.mutable.Builder",
  "-keep public class scala.Option",
  "-keep class scala.runtime.** { *; }",
  "-keep class com.fasterxml.jackson.databind.** { *; }",
  "-keep interface com.fasterxml.jackson.databind.** { *; }",
  "-keepclassmembers class * { ** MODULE$; }",
  "-keepclassmembers class **.R$* {public static <fields>;}",
  "-dontoptimize",
  "-dontwarn scala.collection.mutable.**",
  "-dontwarn org.simpleframewok.xml.**",
  "-dontwarn org.springframework.http.converter.xml.**",
  "-dontwarn org.apache.commons.**",
  "-dontwarn org.codehaus.jackson.**",
  "-dontwarn com.google.gson.**",
  "-dontwarn com.google.code.rome.**",
  "-dontwarn javax.inject.**",
  "-dontwarn com.google.appengine.**",
  "-dontwarn com.google.apphosting.**",
  "-dontwarn sun.misc.Unsafe",
  "-dontwarn org.w3c.dom.**"
)
```

Do you have any hints what I possibly forgot? Or what has to be definitely present, so that "apply()" detection of the jackson scala module works?

Thanks in advance
Chris

**Comment by pnpritchard** [comment]
FYI for anyone who comes across this thread... I was facing the same issue and fixed it with this proguard config: `keepattributes 'LocalVariableTable,RuntimeVisibleAnnotations'`
