### ISSUE TITLE
2.4.4 version of module does not work with jackson 2.5.0

### ISSUE THREAD

**Issue by kgignatyev** [FasterXML/jackson-module-scala#177]
here is simple project to reproduce the problem
https://github.com/kgignatyev/misc/tree/master/jackson-scala-2.5-problem

works with jackson 2.4.4 but with 2.5.0 it produces
 com.fasterxml.jackson.databind.JsonMappingException: Could not find creator property with name 'label' (in class kgi.repro.jacksonscala.LabeledValue)
 at [Source: {"label":"aaaaa","value":"bbbbb"}; line: 1, column: 1]
  at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
  at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:843)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:533)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:220)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:405)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:354)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:262)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:

**Comment by cowtowncoder** [comment]
While it'd be nice to make adjacent minor versions to work with each other, this is something nice-to-have, but not something that we try (or can) guarantee. So whereas all patch versions do need to be compatible with any other combination, same is not true for minor versions: only application-code is forwards-compatible (that is, code written to use Jackson 2.4 should continue to work with Jackson 2.5). But mix of different minor versions of Jackson components may or may not work.

In this particular case it is highly likely that there is no way to make Scala 2.4 module work with both databind 2.4 and 2.5, since there were significant changes in the way databind handles implicit and explicit naming of method/constructor parameters.

@christophercurrie will be able to more specifically determine if there is anything that can be done, but I thought I'll add comments since I am familiar with work on databind side.

**Comment by cowtowncoder** [comment]
This is actually an interesting idea: given that all modules do both indicate their own version (to be checked by `ObjectMapper`), and can also detect version of `ObjectMapper`, it would be quite simple to add explicit verification.

However, question is if and how to allow some combinations; or perhaps make this configurable.
Problem being that due to transitive dependencies many projects end up with slightly incompatible but functioning combinations. For example, many datatype modules are more compatible, that is, working with wide range of versions of core components.

In specific case of Scala module it may be easy to enough to specify that, say, Scala module 2.5 requires databind 2.5. But it is not necessarily possible, a priori, say anything regarding upcoming versions.

So maybe simplest way really is to check for same minor version and throw exception; unless a specific method has been called on module (or constructor) to allow discrepancy.

**Comment by kgignatyev** [comment]
It is not easy, but would be nice if (eventual) alignment with http://semver.org/ was possible then modules could specify their expectations

**Comment by christophercurrie** [comment]
I've put in a version check that will go out with 2.5, and 2.4.5 should that ever be released.
