### ISSUE TITLE
Deserializing string to Seq[Case Class] returns Seq[HashMap]

### ISSUE THREAD

**Issue by mrmeyers99** [FasterXML/jackson-module-scala#187]
The following test shows that deserializing a string to a Seq[Case Class] returns a Seq[HashMap] instead.

```
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import org.specs2.mutable.Specification

case class Person(name: String, age: Int)

class ScalaModuleCaseClassSpec extends Specification {

  val mapper = new ObjectMapper().registerModule(DefaultScalaModule)

  val singleString = """{"name": "John Doe", "age": 32}"""
  val arrayString =
    """
      |[
      |  {"name": "John Doe", "age": 32},
      |  {"name": "Jane Doe", "age": 32}
      |]
    """.stripMargin

  "DefaultScalaModule" should {
    "convert string to case class" in {
      val john = mapper.readValue(singleString, classOf[Person])
      john === Person("John Doe", 32)
    }
    "convert string to seq of case class" in {
      val people = mapper.readValue(arrayString, classOf[Seq[Person]])
      people === Seq(Person("John Doe", 32), Person("Jane Doe", 32))
    }
  }
}
```

The output is:
```
DefaultScalaModule should
convert string to case class

List(Map(name -> John Doe, age -> 32), Map(name -> Jane Doe, age -> 32))

 is not equal to 

List(Person(John Doe,32), Person(Jane Doe,32))
Expected :List(Person(John Doe,32), Person(Jane Doe,32))
Actual   :List(Map(name -> John Doe, age -> 32), Map(name -> Jane Doe, age -> 32))
 <Click to see difference>

java.lang.Exception: List(Map(name -> John Doe, age -> 32), Map(name -> Jane Doe, age -> 32))

 is not equal to 

List(Person(John Doe,32), Person(Jane Doe,32))
	at ScalaModuleCaseClassSpec$$anonfun$1$$anonfun$apply$4.apply(TestScalaModule.scala:28)
	at ScalaModuleCaseClassSpec$$anonfun$1$$anonfun$apply$4.apply(TestScalaModule.scala:25)

convert string to seq of case class
```

Here are my maven dependencies:
```
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-joda</artifactId>
            <version>2.5.1</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-scala_2.10</artifactId>
            <version>2.5.1</version>
        </dependency>

**Comment by mrmeyers99** [comment]
Interestingly, deserializing to Array instead of Seq works as expected:
```
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import org.specs2.mutable.Specification

case class Person(name: String, age: Int)

class ScalaModuleCaseClassSpec extends Specification {

  val mapper = new ObjectMapper().registerModule(DefaultScalaModule)

  val singleString = """{"name": "John Doe", "age": 32}"""
  val arrayString =
    """
      |[
      |  {"name": "John Doe", "age": 32},
      |  {"name": "Jane Doe", "age": 32}
      |]
    """.stripMargin

  "DefaultScalaModule" should {
    "convert string to case class" in {
      val john = mapper.readValue(singleString, classOf[Person])
      john === Person("John Doe", 32)
    }
    "convert string to seq of case class" in {
      val people = mapper.readValue(arrayString, classOf[Seq[Person]])
      people === Seq(Person("John Doe", 32), Person("Jane Doe", 32))
    }
    "convert string to array of case class" in {
      val people = mapper.readValue(arrayString, classOf[Array[Person]])
      people === Array(Person("John Doe", 32), Person("Jane Doe", 32))
    }
  }
}
```

Output:
```
DefaultScalaModule should
convert string to case class

List(Map(name -> John Doe, age -> 32), Map(name -> Jane Doe, age -> 32))

 is not equal to 

List(Person(John Doe,32), Person(Jane Doe,32))
Expected :List(Person(John Doe,32), Person(Jane Doe,32))
Actual   :List(Map(name -> John Doe, age -> 32), Map(name -> Jane Doe, age -> 32))
 <Click to see difference>

java.lang.Exception: List(Map(name -> John Doe, age -> 32), Map(name -> Jane Doe, age -> 32))

 is not equal to 

List(Person(John Doe,32), Person(Jane Doe,32))
	at ScalaModuleCaseClassSpec$$anonfun$1$$anonfun$apply$4.apply(TestScalaModule.scala:27)
	at ScalaModuleCaseClassSpec$$anonfun$1$$anonfun$apply$4.apply(TestScalaModule.scala:25)

convert string to seq of case class
convert string to array of case class
```

**Comment by nbauernfeind** [comment]
This is due to erasure. `classOf[Seq[Person]]` is identical to `classOf[Seq[_]]`. The reason that `classOf[Array[Person]]` works is that Array isn't a real class, but rather it is a flag on the class instance that says it's an array.

There are a few ways to get around this. You can use the experimental ScalaObjectMapper like so:

```scala
val mapper = new ObjectMapper() with ScalaObjectMapper
mapper.registerModule(DefaultScalaModule)

mapper.readValue[Seq[Person]](arrayString)
```

Or you can use TypeReferences yourself.

```scala
mapper.readValue(arrayString, new TypeReference[Seq[Person]]() {})
```

Or you can steal/re-use the method `constructType[T]` from `ScalaObjectMapper.scala` and use it wherever else you like.

**Comment by mrmeyers99** [comment]
Ok, you're right that works.  Thanks for the help.

**Comment by nbauernfeind** [comment]
I know =). You're welcome!
