### ISSUE TITLE
Deserialization fails with existing object (readerForUpdating) 

### ISSUE THREAD

**Issue by migel** [FasterXML/jackson-module-scala#191]
See below. ```d10``` is serialized to json and then successfully deserialized to ```d11``` as a new object. However, trying to update ```d12``` in place fails.

```scala
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import com.fasterxml.jackson.databind.SerializationFeature
import com.fasterxml.jackson.annotation.PropertyAccessor
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility
import com.fasterxml.jackson.databind.ObjectReader

class DataA {
  @JsonProperty var vint: Int = 3
}

object jackson2 {
  println("Welcome to the Scala worksheet")       //> Welcome to the Scala worksheet
  val mapper = new ObjectMapper()                 //> mapper  : com.fasterxml.jackson.databind.ObjectMapper = com.fasterxml.jackso
                                                  //| n.databind.ObjectMapper@679e96f7
  mapper.registerModule(DefaultScalaModule)       //> res0: com.fasterxml.jackson.databind.ObjectMapper = com.fasterxml.jackson.da
                                                  //| tabind.ObjectMapper@679e96f7
  mapper.enable(SerializationFeature.INDENT_OUTPUT)
                                                  //> res1: com.fasterxml.jackson.databind.ObjectMapper = com.fasterxml.jackson.da
                                                  //| tabind.ObjectMapper@679e96f7
  mapper.setVisibility(PropertyAccessor.ALL, Visibility.NONE)
                                                  //> res2: com.fasterxml.jackson.databind.ObjectMapper = com.fasterxml.jackson.da
                                                  //| tabind.ObjectMapper@679e96f7

  val d10 = new DataA                             //> d10  : DataA = DataA@fb9165a
  d10.vint = 5

  val d10Json = mapper.writeValueAsString(d10)    //> d10Json  : String = {
                                                  //|   "vint" : 5
                                                  //| }
  val d11 = mapper.readValue(d10Json, classOf[DataA])
                                                  //> d11  : DataA = DataA@3c22de9e

  val d11Json = mapper.writeValueAsString(d11)    //> d11Json  : String = {
                                                  //|   "vint" : 5
                                                  //| }

  val d12 = new DataA                             //> d12  : DataA = DataA@154575ea
  mapper.readerForUpdating[ObjectReader](d12).readValue(d10Json)
                                                  //> java.lang.ClassCastException: DataA cannot be cast to scala.runtime.Nothing$
                                                  //| 
                                                  //| 	at jackson2$$anonfun$main$1.apply$mcV$sp(jackson2.scala:29)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$$anonfun$$exe
                                                  //| cute$1.apply$mcV$sp(WorksheetSupport.scala:76)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.redirected(W
                                                  //| orksheetSupport.scala:65)
                                                  //| 	at org.scalaide.worksheet.runtime.library.WorksheetSupport$.$execute(Wor
                                                  //| ksheetSupport.scala:75)
                                                  //| 	at jackson2$.main(jackson2.scala:13)
                                                  //| 	at jackson2.main(jackson2.scala)
}
```

**Comment by migel** [comment]
Got it to work when explicitly specifying the type of the object to update:

```scala
  mapper.readerForUpdating[ObjectReader](d12).readValue[DataA](d10Json)
```
Is that expected? The example I found for Java:
```java
  mapper.readerForUpdating(object).readValue(json);
```

**Comment by nbauernfeind** [comment]
What versions of jackson and scala are you using?

It seems to work for jackson 2.5.1 and scala 2.11.6.

**Comment by migel** [comment]
Hi, I'm using 2.5.1 and scala 2.11.6 as well.
I've tested again with a proper test application and it works so it seems to be a bug or limitation of the scala worksheet. Thanks.

**Comment by migel** [comment]
Hi, I've found a case that fails. If the constructor has parameters, object update fails:
```scala
import org.scalatest.FunSuite
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.annotation.PropertyAccessor
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility
import com.fasterxml.jackson.databind.ObjectReader

class Data {
  @JsonProperty var i: Int = 2
}

class DataF(val f: Float) {
  @JsonProperty var i: Int = 2
}

class TestObjectUpdate extends FunSuite {
  test("save/load state") {
    val mapper = new ObjectMapper
    mapper.setVisibility(PropertyAccessor.ALL, Visibility.NONE)

    // Update Data - ok
    val d = new Data
    d.i = 3
    val state = mapper.writeValueAsString(d)

    val d2 = new Data
    mapper.readerForUpdating[ObjectReader](d2).readValue(state)

    // Update DataF - fails on update
    val df = new DataF(2.1f)
    df.i = 3
    val statef = mapper.writeValueAsString(df)

    val df2 = new DataF(2.1f)
    // raises exception
    mapper.readerForUpdating[ObjectReader](df2).readValue(statef)
  }
}
```

**Comment by migel** [comment]
I've found out the cause; it's just scala trying to convert the return value if I add ```None``` as the last line of the test it works.
