### ISSUE TITLE
Deserialization fails when migrating from 2.4 to 2.5

### ISSUE THREAD

**Issue by jans23** [FasterXML/jackson-module-scala#196]
I'm using jackson-module-scala 2.4.5 successfully with the wrapper below to serialize and deserialize various complex objects. When changing to jackson-module-scala 2.5.0 or 2.5.1 many deserializations (JSON to object) fail. For instance, the deserialization of the following simple list fails.

    val myList = MyListClass(List(1,2,3,4))
    val myListJson = "{\n  \"myList\" : [ 1, 2, 3, 4 ]\n}"
    
    // This test succeeds with Jackson 2.5
    test("Serialize List object to JSON string") {
      assertResult(myListJson) { serialize(myList) }
    }
    
    // This test *fails* with Jackson 2.5
    test("Deserialize JSON string to List") {
      assertResult(myList) { deserialize[MyListClass](myListJson) }
    }

The error message:

    Deserialize JSON string to List *** FAILED ***
    com.fasterxml.jackson.databind.JsonMappingException: Argument #0 of constructor [constructor for java.util.LinkedHashMap, annotations: [null]] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:267)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:242)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:143)
    at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:429)
    at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer._findCustomDeser(UntypedObjectDeserializer.java:125)
    at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.resolve(UntypedObjectDeserializer.java:105)
    at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.resolve(UntypedObjectDeserializerModule.scala:23)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:242)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:143)
    ...
    Cause: java.lang.IllegalArgumentException: Argument #0 of constructor [constructor for java.util.LinkedHashMap, annotations: [null]] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator
    at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addDeserializerConstructors(BasicDeserializerFactory.java:508)
    at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:325)
    at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:258)
    at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.createMapDeserializer(BasicDeserializerFactory.java:1099)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:382)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:354)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:262)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:242)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:143)
    at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:429)

This is the wrapper:

    import com.fasterxml.jackson.databind.{DeserializationFeature, SerializationFeature, ObjectMapper}
    import com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper
    import com.fasterxml.jackson.module.scala.DefaultScalaModule
    import com.fasterxml.jackson.databind.module.SimpleModule
    import com.fasterxml.jackson.core.Version
    
    /**
     * Based on: https://coderwall.com/p/o--apg/easy-json-un-marshalling-in-scala-with-jackson
     */
    object JacksonWrapper {
      private val dateFormat = new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'")
    
      val module = new SimpleModule("CustomJson", Version.unknownVersion())
      module.addSerializer(classOf[BigInt], new BigIntSerializer)
      module.addDeserializer(classOf[BigInt], new BigIntDeserializer)
    
      val mapper = new ObjectMapper() with ScalaObjectMapper
      mapper.registerModule(DefaultScalaModule)
      mapper.setDateFormat(dateFormat)
      mapper.registerModule(module)
      mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
      mapper.enable(SerializationFeature.INDENT_OUTPUT); //Enable pretty printing
    
      def serialize(value: Map[Symbol, Any]): String = {
        serialize(value map { case (k,v) => k.name -> v})
      }
    
      def serialize(value: Any): String = {
        mapper.writeValueAsString(value)
      }
    
      def toMap[V](json:String)(implicit m: Manifest[V]) = deserialize[Map[String,V]](json)
    
      def deserialize[T](json: String)(implicit m : Manifest[T]): T = {
        mapper.readValue[T](json)
      }
    }

How to migrate to Jackson 2.5 and get the deserialization working?

**Comment by cowtowncoder** [comment]
Which version of 2.4 are you using? Does 2.4.5 (latest official) work?

**Comment by jans23** [comment]
I use 2.4.5 (and now clarified it in my description above).

**Comment by cowtowncoder** [comment]
Thank you for confirming that. I don't know what could cause the issue, but there were some changes in 2.4.4 that caused problems with caching of Map deserializers, so was wondering if those could be related.  But if 2.4.5 works then this does not seem likely.

It sounds more likely this is related to improvements to creator handling in databind. While intent is to reduce need for annotations, it sounds like something broke with Scala module integration.

**Comment by cowtowncoder** [comment]
From the error it looks like Scala module unintentionally indicates that `LinkedHashMap` has `@JsonCreator` annotation. I am guessing that the code path in question was not triggered previously by databind (perhaps it was deferred, and is more eagerly evaluated now?).

**Comment by christophercurrie** [comment]
I'm finally able to reproduce this issue, using a Vagrant VM running Ubuntu and using OpenJDK 1.6. I don't yet have a fix for it, but now have first step towards a solution. I hope to have a fix prepared by the end of the weekend.

**Comment by christophercurrie** [comment]
There is now a snapshot version, 2.5.2-SNAPSHOT, published to the Sonatype OSS snapshot repository. If you are able, could you try this snapshot and see if it resolves your issue?

**Comment by jans23** [comment]
It seems to solve the issue. Thanks a lot.

**Comment by christophercurrie** [comment]
Great, I have a couple of other issue to investigate but I'll get a release with this fix out this week.

**Comment by christophercurrie** [comment]
2.5.2 was released today to fix this issue. Thanks for your report!
