### ISSUE TITLE
JsonTypeInfo.As.EXTERNAL_PROPERTY doesn't work for case classes

### ISSUE THREAD

**Issue by maximn** [FasterXML/jackson-module-scala#200]
Here's a test that shows the problem - 

``` scala
package com.wix.jacksontest

import com.fasterxml.jackson.annotation.JsonSubTypes.Type
import com.fasterxml.jackson.annotation.{JsonSubTypes, JsonTypeInfo}
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import org.specs2.mutable.SpecificationWithJUnit

sealed trait Parent

case class ChildA(dataA: String) extends Parent

case class Wrapper(typ: String,
                   @JsonSubTypes(Array(
                     new Type(value = classOf[ChildA], name = "ChildA")
                   ))
                   @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "typ")
                   polymorphic: Parent)


class JacksonExternalPropertyTest extends SpecificationWithJUnit {
  val mapper = new ObjectMapper().registerModules(DefaultScalaModule)


  "Polymorphic deserialization with EXTERNAL_PROPERTY" should {
    "deserialize object" >> {
      val json = """{"typ":"ChildA", "polymorphic" : { "dataA":"xxx"}}"""
      mapper.readValue(json, classOf[Wrapper]) must be_===(Wrapper(typ = "ChildA", polymorphic = ChildA("xxx")))
    }
  }
}
```

And the error is - 

```
Problem deserializing property 'polymorphic' (expected type: [simple type, class com.wix.jacksontest.Parent]; actual type: com.wix.jacksontest.ChildA), problem: Can not set final com.wix.jacksontest.Parent field com.wix.jacksontest.Wrapper.polymorphic to com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer
com.fasterxml.jackson.databind.JsonMappingException: Problem deserializing property 'polymorphic' (expected type: [simple type, class com.wix.jacksontest.Parent]; actual type: com.wix.jacksontest.ChildA), problem: Can not set final com.wix.jacksontest.Parent field com.wix.jacksontest.Wrapper.polymorphic to com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty._throwAsIOE(SettableBeanProperty.java:565)
    at com.fasterxml.jackson.databind.deser.impl.FieldProperty.set(FieldProperty.java:124)
    at com.fasterxml.jackson.databind.deser.CreatorProperty.set(CreatorProperty.java:224)
    at com.fasterxml.jackson.databind.deser.CreatorProperty.deserializeAndSet(CreatorProperty.java:203)
    at com.fasterxml.jackson.databind.deser.impl.ExternalTypeHandler._deserializeAndSet(ExternalTypeHandler.java:253)
    at com.fasterxml.jackson.databind.deser.impl.ExternalTypeHandler.handlePropertyValue(ExternalTypeHandler.java:120)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeUsingPropertyBasedWithExternalTypeId(BeanDeserializer.java:726)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeWithExternalTypeId(BeanDeserializer.java:650)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:262)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2161)
    at com.wix.jacksontest.JacksonExternalPropertyTest$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(ActivityInfoSerializationTest.scala:28)
    at com.wix.jacksontest.JacksonExternalPropertyTest$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(ActivityInfoSerializationTest.scala:28)
    at com.wix.jacksontest.JacksonExternalPropertyTest$$anonfun$1$$anonfun$apply$1.apply(ActivityInfoSerializationTest.scala:28)
    at com.wix.jacksontest.JacksonExternalPropertyTest$$anonfun$1$$anonfun$apply$1.apply(ActivityInfoSerializationTest.scala:26)
Caused by: java.lang.IllegalArgumentException: Can not set final com.wix.jacksontest.Parent field com.wix.jacksontest.Wrapper.polymorphic to com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
    at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
    at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:77)
    at com.fasterxml.jackson.databind.deser.impl.FieldProperty.set(FieldProperty.java:122)
    ... 14 more
```

From my investigation looks like in -
com.fasterxml.jackson.databind.deser.impl.FieldProperty.set(FieldProperty.java:124)
Trying to use the set method on the `Parent` class using reflection on a wrong instance (PropertyValueBuffer)

If I use -

``` scala
class Wrapper() {
  var typ: String = _

  @JsonSubTypes(Array(
    new Type(value = classOf[ChildA], name = "ChildA")
  ))
  @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "typ")
  var polymorphic: Parent = _
}
```

It will work, but we're in Scala and I want to use case classes.

**Comment by syamantm** [comment]
+1, we also enchanted this issue

**Comment by zilionis** [comment]
+1

**Comment by pjfanning** [comment]
test passes with 2.13 branch code - https://github.com/FasterXML/jackson-module-scala/commit/a9fa640fb13a75b88ab2b7ddb1b7b5b95e9c4409
