### ISSUE TITLE
Deserializing case class: Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class asd$X]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)

### ISSUE THREAD

**Issue by radoslawtwardy** [FasterXML/jackson-module-scala#208]
I try code
```
case class X(test: String)

val scalaMapper= new ObjectMapper()
scalaMapper.registerModule(DefaultScalaModule)
scalaMapper.setSerializationInclusion(Include.NON_NULL)
scalaMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
scalaMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, true)
scalaMapper.configure(DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES, true)

val str = """{"test":"testValue"}"""
val obj =  scalaMapper.readValue(str2, classOf[X])
```

And i get exception
```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class asd$X]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: {"test":"testValue"}; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1080)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at scala.com.comarch.bss.restapi.om.asd$delayedInit$body.apply(asd.scala:52)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at scala.com.comarch.bss.restapi.om.asd$.main(asd.scala:8)
	at scala.com.comarch.bss.restapi.om.asd.main(asd.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

Serializing:
```
scalaMapper.writeValueAsString(new X("testValue"))
```
is working properly

I try use jackson in version 2.3.1 and 2.5.2 - in project I use scala 2.10.4

In jackson 2.2.3 everything works fine

**Comment by christophercurrie** [comment]
From the stack trace, it looks like the actual class you're trying to serialize is a nested class, but your code sample doesn't provide enough context for me to know for sure. If the class is moved to the package level, the example should work.

Background: Scala doesn't provide reflection support for nested classes, so `X` doesn't "look like" a Scala class, so the Scala module ignores it. Core jackson requires (in some cases) the `@JsonCreator` annotation to know how to construct the type; normally the Scala module provides assistance, but doesn't in this case.

Potential workaround: add annotations to your type:

``` scala
case class X @JsonCreator() (@JsonProperty("test") test: String)
```

Note that if your type nested within a class or a method, this will probably not work anyway, as Jackson can't create objects in those nested contexts. Only types that are nested in companion objects can be deserialized. If you need to deserialize a nested type, you're going to need to provide an existing instance of the type to deserialize into:

``` scala
val x = X("dummy")
val reader: ObjectReader = scalaMapper.readerForUpdating(x)
reader.readValue(str)
```

This *should* work, but it might not until FasterXML/jackson-databind#807 gets fixed.

**Comment by radoslawtwardy** [comment]
Class X in declared inside the object in my example. If class X is outside i have still same problem
'''
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class scala.com.comarch.bss.restapi.om.X]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: {"test":"testValue"}; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1080)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at scala.com.comarch.bss.restapi.om.asd$delayedInit$body.apply(asd.scala:54)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at scala.com.comarch.bss.restapi.om.asd$.main(asd.scala:22)
	at scala.com.comarch.bss.restapi.om.asd.main(asd.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
'''

If I add annotiations @JsonCreator, @JsonProperty everything works fine, but it complicating my real objects which i wont serialize - i have tens of class, hundreds of fields. 

I don't understand why this very simple example don't work without these annotations

**Comment by cowtowncoder** [comment]
@radoslawtwardy Core Jackson does not like the fact that your original inner class has conflicting definition (from its perspective). Non-static inner classes have the hidden 'this' pointer, as the first argument. Same should not occur if this is either static inner class, or main-level class.
As to why the exception is thrown for serialization use case is bit more difficult to say; Jackson will try to combine information for both sides, to avoid need to explicitly annotate both getters and setters, and this results in discrepancy being noted and reported (since it seems like a broken definition).

Above is just to explain how this happens; intention is not to block serialization in this case. But while the use case is simple from user perspective it is quite complicated under the hood.
And this is why @christophercurrie is suggesting work-arounds on short term to enable you to get things working now, and have time to figure out how things can be improved to avoid needing to use additional annotations.

**Comment by radoslawtwardy** [comment]
My problem is caused by incompatible dependencies in my IDE. It use antother version of core and another of scala module. Sorry for dealing time and thanks for answers
