### ISSUE TITLE
deserialization of option in class fails

### ISSUE THREAD

**Issue by migel** [FasterXML/jackson-module-scala#220]
I have a data member of type `Option[RandomGenerator]` in a class that fails to deserialize:

``` scala
import org.apache.commons.math3.random.RandomGenerator

class Rng {
  var rng: Option[RandomGenerator] = None
}

object test {

  val objectMapper = new ObjectMapper {
    enable(SerializationFeature.INDENT_OUTPUT)
    registerModule(DefaultScalaModule)
  }                                               //> objectMapper  : com.fasterxml.jackson.databind.ObjectMapper = test$$anonfun
                                                  //| $main$1$$anon$1@29176cc1

  val rng2 = new Rng()                            //> rng2  : Rng = Rng@2ddc8ecb

  val rng2json = objectMapper.writeValueAsString(rng2)
                                                  //> rng2json  : String = {
                                                  //|   "rng" : null
                                                  //| }
  objectMapper.readValue(rng2json, classOf[Rng])  //> com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter def
                                                  //| initions for property "seed": org.apache.commons.math3.random.RandomGenerat
                                                  //| or#setSeed(1 params) vs org.apache.commons.math3.random.RandomGenerator#set
                                                  //| Seed(1 params)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCach
                                                  //| e2(DeserializerCache.java:269)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCach
                                                  //| eValueDeserializer(DeserializerCache.java:244)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeser
                                                  //| ializer(DeserializerCache.java:142)
                                                  //|   at com.fasterxml.jackson.databind.DeserializationContext.findContextualV
                                                  //| alueDeserializer(DeserializationContext.java:428)
                                                  //|   at com.fasterxml.jackson.module.scala.deser.OptionDeserializer.createCon
                                                  //| textual(OptionDeserializerModule.scala:28)
                                                  //|   at com.fasterxml.jackson.databind.DeserializationContext.handleSecondary
                                                  //| Contextualization(DeserializationContext.java:669)
                                                  //|   at com.fasterxml.jackson.databind.DeserializationContext.findContextualV
                                                  //| alueDeserializer(DeserializationContext.java:430)
                                                  //|   at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserial
                                                  //| izer(StdDeserializer.java:947)
                                                  //|   at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(Bea
                                                  //| nDeserializerBase.java:439)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCach
                                                  //| e2(DeserializerCache.java:296)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCach
                                                  //| eValueDeserializer(DeserializerCache.java:244)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeser
                                                  //| ializer(DeserializerCache.java:142)
                                                  //|   at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDe
                                                  //| serializer(DeserializationContext.java:461)
                                                  //|   at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(Obj
                                                  //| ectMapper.java:3804)
                                                  //|   at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMa
                                                  //| pper.java:3698)
                                                  //|   at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.ja
                                                  //| va:2714)
                                                  //|   at test$$anonfun$main$1.apply$mcV$sp(test.scala:37)
                                                  //|   at org.scalaide.worksheet.runtime.library.WorksheetSupport$$anonfun$$exe
                                                  //| cute$1.apply$mcV$sp(WorksheetSupport.scala:76)
                                                  //|   at org.scalaide.worksheet.runtime.library.WorksheetSupport$.redirected(W
                                                  //| orksheetSupport.scala:65)
                                                  //|   at org.scalaide.worksheet.runtime.library.WorksheetSupport$.$execute(Wor
                                                  //| ksheetSupport.scala:75)
                                                  //|   at test$.main(test.scala:27)
                                                  //|   at test.main(test.scala)
                                                  //| Caused by: java.lang.IllegalArgumentException: Conflicting setter definitio
                                                  //| ns for property "seed": org.apache.commons.math3.random.RandomGenerator#set
                                                  //| Seed(1 params) vs org.apache.commons.math3.random.RandomGenerator#setSeed(1
                                                  //|  params)
                                                  //|   at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSett
                                                  //| er(POJOPropertyBuilder.java:299)
                                                  //|   at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.filterBe
                                                  //| anProps(BeanDeserializerFactory.java:592)
                                                  //|   at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanP
                                                  //| rops(BeanDeserializerFactory.java:488)
                                                  //|   at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBea
                                                  //| nDeserializer(BeanDeserializerFactory.java:229)
                                                  //|   at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBe
                                                  //| anDeserializer(BeanDeserializerFactory.java:142)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeseria
                                                  //| lizer2(DeserializerCache.java:403)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeseria
                                                  //| lizer(DeserializerCache.java:352)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCach
                                                  //| e2(DeserializerCache.java:264)
                                                  //|   ... 21 more
}
```

What I actually want to do is to serialize an option holding a polymorphic type. When done directly on a var (see `rng3`) it fails to return the correct type; it returns a map instead (see `res2`). If it's a member of a class (see `rng4`) it fails with an exception:

``` scala
import org.apache.commons.math3.random.RandomGenerator     // interface
import org.apache.commons.math3.random.BitsStreamGenerator // implements RandomGenerator
import org.apache.commons.math3.random.MersenneTwister // Subclass of BitsStreamGenerator

class Rng {
  var rng: Option[RandomGenerator] = None
}

@JsonAutoDetect(
  fieldVisibility = Visibility.ANY,
  getterVisibility = Visibility.NONE,
  setterVisibility = Visibility.NONE)
class BitsStreamGeneratorMixIn {}

@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
class RandomGeneratorMixIn {}

object test {

  val objectMapper = new ObjectMapper {
    enable(SerializationFeature.INDENT_OUTPUT)
    registerModule(DefaultScalaModule)
  }                                               //> objectMapper  : com.fasterxml.jackson.databind.ObjectMapper = test$$anonfun
                                                  //| $main$1$$anon$1@29176cc1

  objectMapper.addMixIn(
    classOf[BitsStreamGenerator],
    classOf[BitsStreamGeneratorMixIn])            //> res0: com.fasterxml.jackson.databind.ObjectMapper = test$$anonfun$main$1$$a
                                                  //| non$1@29176cc1
  objectMapper.addMixIn(
    classOf[RandomGenerator],
    classOf[RandomGeneratorMixIn])                //> res1: com.fasterxml.jackson.databind.ObjectMapper = test$$anonfun$main$1$$a
                                                  //| non$1@29176cc1

  val rng3: Option[RandomGenerator] = Some(new MersenneTwister(0))
                                                  //> rng3  : Option[org.apache.commons.math3.random.RandomGenerator] = Some(org.
                                                  //| apache.commons.math3.random.MersenneTwister@5276e6b0)
  val rng3json = objectMapper.writeValueAsString(rng3)
                                                  //> rng3json  : String = {
                                                  //|   "nextGaussian" : "NaN",
                                                  //|   "mt" : [ 0, 1, 1812433255, 1900727105, 1208447044, -1813563330, -25235975
                                                  //| 8, 337614300, -1062413356, 1018809052, -1092565802, 1775180719, -1102575182
                                                  //| , 594215549, 184016991, 829906058, 610491522, -415035045, -1155141686, 2979
                                                  //| ...
                                                  //| 8183364, -626918563, 2030009470, 1910839172, 1234925283, -719135851, 123595
                                                  //| 418, -1932526801, -1246482385, 1796872496 ],
                                                  //|   "mti" : 624
                                                  //| }
  objectMapper.readValue(rng3json, classOf[Option[RandomGenerator]])
                                                  //> res2: Option[org.apache.commons.math3.random.RandomGenerator] = Some(Map(ne
                                                  //| xtGaussian -> NaN, mt -> List(0, 1, 1812433255, 1900727105, 1208447044, -18
                                                  //| 13563330, -252359758, 337614300, -1062413356, 1018809052, -1092565802, 1775
                                                  //| 180719, -1102575182, 594215549, 184016991, 829906058, 610491522, -415035045
                                                  //| ...
                                                  //| 0168, 1686857206, 1112632275, 1200680507, -952039100, -1617909146, 93944213
                                                  //| 6, -887862627, -1388183364, -626918563, 2030009470, 1910839172, 1234925283,
                                                  //|  -719135851, 123595418, -1932526801, -1246482385, 1796872496), mti -> 624))
                                                  //| 

  val rng4 = new Rng()                            //> rng4  : Rng = Rng@46fa7c39
  rng4.rng = Some(new MersenneTwister(0))
  val rng4json = objectMapper.writeValueAsString(rng4)
                                                  //> rng4json  : String = {
                                                  //|   "rng" : {
                                                  //|     "@class" : "org.apache.commons.math3.random.MersenneTwister",
                                                  //|     "nextGaussian" : "NaN",
                                                  //|     "mt" : [ 0, 1, 1812433255, 1900727105, 1208447044, -1813563330, -252359
                                                  //| 758, 337614300, -1062413356, 1018809052, -1092565802, 1775180719, -11025751
                                                  //| 82, 594215549, 184016991, 829906058, 610491522, -415035045, -1155141686, 29
                                                  //| ...
                                                  //| 388183364, -626918563, 2030009470, 1910839172, 1234925283, -719135851, 1235
                                                  //| 95418, -1932526801, -1246482385, 1796872496 ],
                                                  //|     "mti" : 624
                                                  //|   }
                                                  //| }
  objectMapper.readValue(rng4json, classOf[Rng])  //> com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter def
                                                  //| initions for property "seed": org.apache.commons.math3.random.RandomGenerat
                                                  //| or#setSeed(1 params) vs org.apache.commons.math3.random.RandomGenerator#set
                                                  //| Seed(1 params)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCach
                                                  //| e2(DeserializerCache.java:269)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCach
                                                  //| eValueDeserializer(DeserializerCache.java:244)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeser
                                                  //| ializer(DeserializerCache.java:142)
                                                  //|   at com.fasterxml.jackson.databind.DeserializationContext.findContextualV
                                                  //| alueDeserializer(DeserializationContext.java:428)
                                                  //|   at com.fasterxml.jackson.module.scala.deser.OptionDeserializer.createCon
                                                  //| textual(OptionDeserializerModule.scala:28)
                                                  //|   at com.fasterxml.jackson.databind.DeserializationContext.handleSecondary
                                                  //| Contextualization(DeserializationContext.java:669)
                                                  //|   at com.fasterxml.jackson.databind.DeserializationContext.findContextualV
                                                  //| alueDeserializer(DeserializationContext.java:430)
                                                  //|   at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserial
                                                  //| izer(StdDeserializer.java:947)
                                                  //|   at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(Bea
                                                  //| nDeserializerBase.java:439)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCach
                                                  //| e2(DeserializerCache.java:296)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCach
                                                  //| eValueDeserializer(DeserializerCache.java:244)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeser
                                                  //| ializer(DeserializerCache.java:142)
                                                  //|   at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDe
                                                  //| serializer(DeserializationContext.java:461)
                                                  //|   at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(Obj
                                                  //| ectMapper.java:3804)
                                                  //|   at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMa
                                                  //| pper.java:3698)
                                                  //|   at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.ja
                                                  //| va:2714)
                                                  //|   at test$$anonfun$main$1.apply$mcV$sp(test.scala:64)
                                                  //|   at org.scalaide.worksheet.runtime.library.WorksheetSupport$$anonfun$$exe
                                                  //| cute$1.apply$mcV$sp(WorksheetSupport.scala:76)
                                                  //|   at org.scalaide.worksheet.runtime.library.WorksheetSupport$.redirected(W
                                                  //| orksheetSupport.scala:65)
                                                  //|   at org.scalaide.worksheet.runtime.library.WorksheetSupport$.$execute(Wor
                                                  //| ksheetSupport.scala:75)
                                                  //|   at test$.main(test.scala:43)
                                                  //|   at test.main(test.scala)
                                                  //| Caused by: java.lang.IllegalArgumentException: Conflicting setter definitio
                                                  //| ns for property "seed": org.apache.commons.math3.random.RandomGenerator#set
                                                  //| Seed(1 params) vs org.apache.commons.math3.random.RandomGenerator#setSeed(1
                                                  //|  params)
                                                  //|   at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSett
                                                  //| er(POJOPropertyBuilder.java:299)
                                                  //|   at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.filterBe
                                                  //| anProps(BeanDeserializerFactory.java:592)
                                                  //|   at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanP
                                                  //| rops(BeanDeserializerFactory.java:488)
                                                  //|   at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBea
                                                  //| nDeserializer(BeanDeserializerFactory.java:229)
                                                  //|   at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBe
                                                  //| anDeserializer(BeanDeserializerFactory.java:142)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeseria
                                                  //| lizer2(DeserializerCache.java:403)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeseria
                                                  //| lizer(DeserializerCache.java:352)
                                                  //|   at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCach
                                                  //| e2(DeserializerCache.java:264)
                                                  //|   ... 21 more
}
```

**Comment by christophercurrie** [comment]
Very strange. Jackson shouldn't try to create a deserializer for `RandomGenerator` because it's an interface. It's possible the Scala module is interfering with core Jackson's default behavior in this case, as I would expect what you're doing in the second example to work using Java. I'll dig into it and see what I can learn.

**Comment by pjfanning** [comment]
More recent versions of jackson-module-scala try harder to just affect serialization/deserialization of Scala classes. Older versions of jackson-module-scala did not check if classes were Java or Scala based and this led to jackson-module-scala affecting serialization/deserialization of some Java classes.

**Comment by pjfanning** [comment]
Closing this old issue. If it can be reproduced with a recent version of jackson-module-scala, please reopen.
