### ISSUE TITLE
NoSuchElementException trying to serialize my Enumeration object

### ISSUE THREAD

**Issue by thoraage** [FasterXML/jackson-module-scala#225]
I'm experiencing some problems serializing an enumeration object. It seems like the jackson tries to get the '$outer' of my superclass, but it's not there. I've got an enumeration GeneralErrorCode which is one of several implementations of a common interface ErrorCode. I compiled a small example my problem.

I created a sbt-project demonstrating the problem at https://www.dropbox.com/s/e9xwp2vkyt3v9f1/enumeration-jackson-problem.tar.bz2?dl=0

Error:

```
[info]   com.fasterxml.jackson.databind.JsonMappingException: None.get
[info]   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:141)                                                                                                                       
[info]   at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1387)
[info]   at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:889)
[info]   at com.fasterxml.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:635)
[info]   at Test$$anonfun$1.apply$mcV$sp(Test.scala:34)
[info]   at Test$$anonfun$1.apply(Test.scala:32)
[info]   at Test$$anonfun$1.apply(Test.scala:32)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info]   Cause: java.util.NoSuchElementException: None.get
[info]   at scala.None$.get(Option.scala:347)
[info]   at scala.None$.get(Option.scala:345)
[info]   at com.fasterxml.jackson.module.scala.ser.EnumerationSerializer.serialize(EnumerationSerializerModule.scala:29)
[info]   at com.fasterxml.jackson.module.scala.ser.EnumerationSerializer.serialize(EnumerationSerializerModule.scala:27)
[info]   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
[info]   at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1387)
[info]   at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:889)
[info]   at com.fasterxml.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:635)
[info]   at Test$$anonfun$1.apply$mcV$sp(Test.scala:34)
[info]   at Test$$anonfun$1.apply(Test.scala:32)
[info]   ...
```

**Comment by cowtowncoder** [comment]
Which version(s) is this with?

**Comment by thoraage** [comment]
Version 2.6.1

**Comment by christophercurrie** [comment]
Thanks for reporting. I'll take a look and see what can be done.

**Comment by pjfanning** [comment]
I tested with the 2.13 code base and can't reproduce this issue
