### ISSUE TITLE
Support jackson-databind 2.7

### ISSUE THREAD

**Issue by omervk** [FasterXML/jackson-module-scala#233]
When trying to use v2.7, I get an exception:

```
com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.7.0
	at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:64) ~[jackson-module-scala_2.11-2.6.3.jar:na]
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:19) ~[jackson-module-scala_2.11-2.6.3.jar:na]
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:722) ~[jackson-databind-2.7.0.jar:2.7.0]
```

As the latest versions of some of my other dependencies rely on 2.7, I'd really appreciate jackson-module-scala support for it too.

**Comment by crumbpicker** [comment]
+1

For me the problem is that this issue has only be solved in 2.7.x
https://github.com/FasterXML/jackson-databind/issues/849#issuecomment-182447320

**Comment by cowtowncoder** [comment]
At this point, there is no one maintaining this module, so the only way 2.7 release can be made is by someone becoming new maintainer. I will keep this issue open but thought it good to mention that no work is on-going to do anything.

Conversely if someone with bit of Scala/SBT-fu is able and willing to help, a new release could be easy to get out. If and when.

**Comment by crumbpicker** [comment]
I can try to help to release a 2.7 compatible version but I would need to know some information about the main API differences between 2.6 and 2.7.

**Comment by cowtowncoder** [comment]
@crumbpicker first step might be just to compile it, run unit tests. All the changes are listed in release notes for `jackson-databind` (release-notes/VERSION), but that won't necessarily help a lot in knowing the areas. The biggest changes are for type resolution and interaction with `TypeFactory`. But there is probably some leftover technical debt wrt using (or rather, not) of other improvements in databind -- Scala module has had various work-arounds for things like support `Option`(al?) type for example; and 2.6 added `ReferenceType`.

**Comment by crumbpicker** [comment]
Ok I have forked the repo. As you suggested I will start by having a look to failing unit tests.
Stay tuned !

**Comment by cowtowncoder** [comment]
@crumbpicker sounds positively awesome -- thank you in advance.

**Comment by mancvso** [comment]
Any news about a 2.7.x release?

**Comment by crumbpicker** [comment]
Still need time to try to work on this. But any help is welcomed !

**Comment by mancvso** [comment]
Can you point me to some task or failing test, any advice to kick-start?

**Comment by crumbpicker** [comment]
I think should ask to @cowtowncoder who is one of the main jackson dev.
I'm just a user of this library but I would not like to see this lib unmaintained.
I didn't managed to start the debug process because I'm very busy at the moment.
So if you have to time to have a look it would be very helpful !

**Comment by mancvso** [comment]
At first sight it seems that neither ```jackson-datatype-joda``` ```jackson-datatype-guava``` ```jackson-module-jsonSchema``` have releases for the 2.7.2 branch (not even in snapshots).
```jackson-module-paranamer``` is not released for 2.7.2 either.

When doing ```sbt test``` I get a pretty NPE
```
java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at $e76e3d565530af28ad59$.java6Home$lzycompute(build.sbt:18)
	at $e76e3d565530af28ad59$.java6Home(build.sbt:18)
	at $e3e8be3b8c6465d1c968$$anonfun$$sbtdef$1.apply(/home/mancvso/Code/jackson-module-scala/build.sbt:23)
	at $e3e8be3b8c6465d1c968$$anonfun$$sbtdef$1.apply(/home/mancvso/Code/jackson-module-scala/build.sbt:20)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:javacOptions) java.lang.NullPointerException
```

**Comment by mancvso** [comment]
Test can run now, but I wonder that if I use previous 2.7.1 versions the results would be invalid with current 2.7.2 versions (let alone 2.8.x)

Anyways, some failing tests are shown, so I can start tinkering.
```
- should support map keys *** FAILED ***
[info]   com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of scala.collection.immutable.Map out of START_OBJECT token
[info]  at [Source: {"value":{"1":"one"}}; line: 1, column: 10] (through reference chain: com.fasterxml.jackson.module.scala.deser.AnnotatedHashKeyLong["value"])
[info]   at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:873)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:869)
[info]   at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:327)
[info]   at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
[info]   at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
[info]   at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:78)
[info]   at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:61)
[info]   at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
[info]   at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
[info]   ...
```
```
[info] - should support map values *** FAILED ***
[info]   com.fasterxml.jackson.databind.JsonMappingException: Failed to narrow value type of [collection-like type; class scala.collection.immutable.Map, contains [simple type, class scala.Tuple2<java.lang.String,java.lang.Object>]] with concrete-type annotation (value java.lang.Long), from '': Class java.lang.Long not subtype of [simple type, class scala.Tuple2<java.lang.String,java.lang.Object>]
[info]   at com.fasterxml.jackson.databind.AnnotationIntrospector.refineDeserializationType(AnnotationIntrospector.java:1135)
[info]   at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.refineDeserializationType(AnnotationIntrospectorPair.java:613)
[info]   at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.refineDeserializationType(AnnotationIntrospectorPair.java:613)
[info]   at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.modifyTypeByAnnotation(BasicDeserializerFactory.java:1844)
[info]   at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.constructCreatorProperty(BasicDeserializerFactory.java:852)
[info]   at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addDeserializerConstructors(BasicDeserializerFactory.java:425)
[info]   at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:321)
[info]   at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:252)
[info]   at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:221)
[info]   at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
[info]   ...
[info]   Cause: java.lang.IllegalArgumentException: Class java.lang.Long not subtype of [simple type, class scala.Tuple2<java.lang.String,java.lang.Object>]
[info]   at com.fasterxml.jackson.databind.type.TypeFactory.constructSpecializedType(TypeFactory.java:332)
[info]   at com.fasterxml.jackson.databind.AnnotationIntrospector.refineDeserializationType(AnnotationIntrospector.java:1132)
[info]   at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.refineDeserializationType(AnnotationIntrospectorPair.java:613)
[info]   at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.refineDeserializationType(AnnotationIntrospectorPair.java:613)
[info]   at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.modifyTypeByAnnotation(BasicDeserializerFactory.java:1844)
[info]   at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.constructCreatorProperty(BasicDeserializerFactory.java:852)
[info]   at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._addDeserializerConstructors(BasicDeserializerFactory.java:425)
[info]   at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:321)
[info]   at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:252)
[info]   at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:221)
[info]   ...
```
```
- should deserialize an annotated Enumeration as a key *** FAILED ***
[info]   com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of scala.collection.immutable.Map out of START_OBJECT token
[info]  at [Source: {"weekdayMap":{"Mon":"Boo","Fri":"Hooray!"}}; line: 1, column: 15] (through reference chain: com.fasterxml.jackson.module.scala.deser.EnumMapHolder["weekdayMap"])
[info]   at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:873)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:869)
[info]   at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:327)
[info]   at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
[info]   at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
[info]   at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:78)
[info]   at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:61)
[info]   at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
[info]   at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
[info]   ...
```
```
- should locate the annotation on BeanProperty fields *** FAILED ***
[info]   com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of scala.collection.immutable.Map out of START_OBJECT token
[info]  at [Source: {"weekdayMap":{"Mon":"Boo","Fri":"Hooray!"}}; line: 1, column: 15] (through reference chain: com.fasterxml.jackson.module.scala.deser.HolderImpl["weekdayMap"])
[info]   at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:873)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:869)
[info]   at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:327)
[info]   at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
[info]   at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
[info]   at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:78)
[info]   at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:61)
[info]   at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
[info]   at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
[info]   ...
```
```
- should deserialize to an immutable.Map by default *** FAILED ***
[info]   com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of scala.collection.immutable.Map out of START_OBJECT token
[info]  at [Source: {"sKey":"sValue","mKey":{"mData":"mValue"}}; line: 1, column: 1]
[info]   at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:873)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:869)
[info]   at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:327)
[info]   at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
[info]   at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
[info]   at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:78)
[info]   at com.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:61)
[info]   at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
[info]   at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2798)
[info]   ...
```

```
 - should serialize a Map[Int] *** FAILED ***
[info]   "{"[traversableAgain":true,"empty":false]}" was not equal to "{"[1":2,"3":4]}", and "{"[traversableAgain":true,"empty":false]}" was not equal to "{"[3":4,"1":2]}" (IterableSerializerTest.scala:77)
```

```
[info] *** 15 TESTS FAILED ***
[error] Failed tests:
[error] 	com.fasterxml.jackson.module.scala.ser.EnumerationSerializerTest
[error] 	com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializerTest
[error] 	com.fasterxml.jackson.module.scala.deser.PrimitiveContainerTest
[error] 	com.fasterxml.jackson.module.scala.deser.EnumerationDeserializerTest
[error] 	com.fasterxml.jackson.module.scala.ser.IterableSerializerTest
[error] 	com.fasterxml.jackson.module.scala.ser.MapSerializerTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 102 s, completed Feb 23, 2016 2:23:33 PM
```

**Comment by nbauernfeind** [comment]
I've actually already upgraded master to work for 2.7, but it requires a minor change to jackson databind (I tested by installing 2.7.2 snapshots locally). This is why the build.sbt is pointing to 2.7.2 (the next-to-be released version of databind). @cowtowncoder Do you know how soon we might be able to start the release cycle?

**Comment by cowtowncoder** [comment]
I am hoping to cut 2.7.2 release sometime this week, or possibly weekend.
Until then, Scala module should use 2.7.2-SNAPSHOT.

**Comment by cowtowncoder** [comment]
@nbauernfeind Just release 2.7.2 of core, so should be possible now.

**Comment by cowtowncoder** [comment]
Fow what it is worth, 2.7.2. of core components has been released now.

**Comment by nbauernfeind** [comment]
Jackson-module-scala 2.7.2 has been released and should make its way to maven central within a few hours.

**Comment by omervk** [comment]
Thank you! :+1:

**Comment by crumbpicker** [comment]
@nbauernfeind: yes thank you very much !
The only problem I had is the issue #238
So I can't use this version yet until I find a workaround or a fix.

**Comment by ookagan** [comment]
I am experiencing this same issue on latest version 2.8.7.

Cause: com.fasterxml....JsonMappingException: Incompatible Jackson version: 2.8.7 [info]   at com.fasterxml....scala.JacksonModule$class.setupModule(JacksonModule.scala:64) [info]   at com.fasterxml....scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:19)[info]   at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:745)

This is my build.sbt:

scalaVersion := "2.11.8"
libraryDependencies += "com.fasterxml.jackson.dataformat" % "jackson-dataformat-xml" % "2.8.7" 
libraryDependencies += "com.fasterxml.jackson.core" % "jackson-core" % "2.8.7"
libraryDependencies += "com.fasterxml.jackson.core" % "jackson-databind" % "2.8.7"
libraryDependencies += "com.fasterxml.jackson.core" % "jackson-annotations" % "2.8.7"

This is my dependency tree:
[info] com...:spark-salesforce_2.11:1.1 [S]
[info]   +-com.fasterxml.jackson.core:jackson-annotations:2.8.0 (evicted by: 2.8.7)
[info]   +-com.fasterxml.jackson.core:jackson-annotations:2.8.7
[info]   +-com.fasterxml.jackson.core:jackson-core:2.8.7
[info]   +-com.fasterxml.jackson.core:jackson-databind:2.8.7
[info]     +-com.fasterxml.jackson.core:jackson-annotations:2.8.0 (evicted by: 2.8.7)
[info]     +-com.fasterxml.jackson.core:jackson-annotations:2.8.7
[info]     +-com.fasterxml.jackson.core:jackson-core:2.8.7

I wonder if this is scala compability issue.

**Comment by ookagan** [comment]
Adding module dependency explicitly fixed my issue:
   libraryDependencies += "com.fasterxml.jackson.module" % "jackson-module-scala_2.11" % "2.8.7"

**Comment by cowtowncoder** [comment]
@ookagan Thank you for adding the update. Yes, I did not realize that you hadn't explicitly specified Scala module version. It is odd that Scala module does not indicate its own version, I thought that had been added in the exception message. Apparently not; if not, should be, to make it much easier to see which version is not up to expected.

**Comment by ookagan** [comment]
cowtowncoder, it took me a lot of digging to figure out what the issue was. Would be great if the error message was more explicit.

After fixing that I got this runtime error when using that library in data bricks cloud:

	at linea09d6e6bc9f24a93b680c94bea1614b5103.$eval$.$print(<console>:6)
17/02/28 03:14:38 ERROR Uncaught throwable from user code: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.SerializationConfig.withDefaultPrettyPrinter(Lcom/fasterxml/jackson/core/PrettyPrinter;)Lcom/fasterxml/jackson/databind/SerializationConfig;
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:86)
	at com.fasterxml.jackson.dataformat.xml.XmlMapper.<init>(XmlMapper.java:67)

All my dependencies point to the latest 2.8.7 release, so I was not expecting to have more issues.
I did not have a chance to dig into this in detail, but if anyone has quick suggestion, I will appreciate it.

**Comment by cowtowncoder** [comment]
@ookagan I agree. What could help is filing a targeted issue wrt "please add version information about Scala module itself in exception about incompatibility", and link to this issue. Most developers do not look for closed issues; and while I see updates, I do not work on Scala module. Nor can I really do much to get things done: this is a volunteer project with unpredictable time availability by developers. This is why visibility is important: open issues with clear titles, all the information -- or best of all, PR -- is the key to get improvements added.

As to error: you are using XML module (`jackson-dataformat-xml`), and its version is incompatible: it has been compiled with version of `jackson-databind` different from one you are using (probably older since you are using latest 2.8).
Since you didn't seem to have version specified in your sbt settings, you will probably need to include it as well.
