### ISSUE TITLE
Internal classes aren't deserialized

### ISSUE THREAD

**Issue by takiri** [FasterXML/jackson-module-scala#286]
Hi,

I've had issues de-serializing a class, see error trace below.
I found out that it couldn't be deserialized because it was defined inside a trait:

``` scala
trait IMyTrait{
    // ...
    case class MyClass(
        @FieldDescription(content = "Param1 desc")
        param1: String
    )
}
```

So, as a workaround, I got my case class out of the trait, and it works this way:

``` scala
case class MyClass(
    @FieldDescription(content = "Param desc")
    param1: String
  )
trait IMyTrait{
   ...
}
```

Is that a limitation of the module? Can it be handled?
Thanks in advance!

Error trace (aliased):

```
java.lang.IllegalArgumentException: Instantiation of [simple type, class fr.path.IMyTrait$MyClass] value failed (java.lang.NullPointerException): null
 at [Source: N/A; line: -1, column: -1] (through reference chain: Object[][0])
    at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3512) ~[jackson-databind-2.7.2.jar:2.7.2]
    at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3431) ~[jackson-databind-2.7.2.jar:2.7.2
  [...]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class fr.path.IMyTrait$MyClass] value failed (java.lang.NullPointerException): null
 at [Source: N/A; line: -1, column: -1] (through reference chain: Object[][0])
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:223) ~[jackson-databind-2.7.2.jar:2.7.2]
    at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:445) ~[jackson-databind-2.7.2.jar:2.7.2]
    at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:464) ~[jackson-databind-2.7.2.jar:2.7.2]
    at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:258) ~[jackson-databind-2.7.2.jar:2.7.2]
    at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:135) ~[jackson-databind-2.7.2.jar:2.7.2]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:444) ~[jackson-databind-2.7.2.jar:2.7.2]
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123) ~[jackson-databind-2.7.2.jar:2.7.2]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298) ~[jackson-databind-2.7.2.jar:2.7.2]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133) ~[jackson-databind-2.7.2.jar:2.7.2]
    at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:196) ~[jackson-databind-2.7.2.jar:2.7.2]
    at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20) ~[jackson-databind-2.7.2.jar:2.7.2]
    at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3507) ~[jackson-databind-2.7.2.jar:2.7.2]
    ... 18 common frames omitted
Caused by: java.lang.NullPointerException: null
    at fr.path.IMyTrait$MyClass.<init>(ClassService.scala:138)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_51]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_51]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_51]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_51]
    at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:114) ~[jackson-databind-2.7.2.jar:2.7.2]
    at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:256) ~[jackson-databind-2.7.2.jar:2.7.2]
    ... 26 common frames omitted
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: net.minidev.json.JSONArray.class
    at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109) ~[rxjava-1.1.9.jar:1.1.9]
    at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73) ~[rxjava-1.1.9.jar:1.1.9]
    ... 11 common frames omitted
```

**Comment by nbauernfeind** [comment]
This is because the case class inside of a trait holds on to a reference of the particular instance of a trait. Perhaps you meant to put your case class inside of a companion object?

```scala
object IMyTrait {
    case class MyClass(
        @FieldDescription(content = "Param1 desc")
        param1: String
    )
}

trait IMyTrait{
    // ...
}
```

You can see that it is impossible to create an instance of your case class without an instance of the trait:
```
scala> trait T { case class C(a: Int) }
defined trait T

scala> T.C(5)
<console>:12: error: not found: value T
       T.C(5)
       ^
scala> new T(){}.C(5)
res3: T#C = C(5)
```

Which, obviously differs from:
```
scala> object T { case class C(a: Int) }
defined object T

scala> T.C(5)
res4: T.C = C(5)
```

**Comment by nbauernfeind** [comment]
Note that serialization does/should work because once you have an instance of the inner class you might as well try your best =).
