### ISSUE TITLE
Expecting List of Int, getting List of Strings

### ISSUE THREAD

**Issue by brainoutsource** [FasterXML/jackson-module-scala#371]
Consider the following code:

```scala
case class MyCaseClass(ids: List[Int])

val mapper: ObjectMapper with ScalaObjectMapper

val myObj = mapper.readValue[MyCaseClass]("""
    {"ids": ["1","2","3"]}
""")
```

Turns out, `myObj.ids` is actually a list of strings:

```scala
myObj.ids.map(_ + 1)
```

results in

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101)
	at scala.runtime.java8.JFunction1$mcII$sp.apply(JFunction1$mcII$sp.java:12)
	at scala.collection.immutable.List.map(List.scala:283)
```

**Comment by nbauernfeind** [comment]
This is, unfortunately known and related to #368 / #243. I'm going to close as a duplicate.
