### ISSUE TITLE
Wrong serializer is used for optional enumerations where only one has JsonScalaEnumeration annotation

### ISSUE THREAD

**Issue by ajhcpt** [FasterXML/jackson-module-scala#403]
If there are two optional enumerations and only the first has the @JsonScalaEnumeration applied, it seems like when looking for a serializer for the second enum the existing AnnotatedEnumerationSerializer for the previous enum is used. 

```scala
case class Test1(@JsonScalaEnumeration(classOf[NumbersTypeReference])
                 numbers: Numbers,
                 days: Days)

case class Test2(@JsonScalaEnumeration(classOf[NumbersTypeReference])
                 numbers: Option[Numbers],
                 days: Option[Days])

class NumbersTypeReference extends TypeReference[Numbers.type]

object Numbers extends Enumeration {
  type Numbers = Value
  val One = Value
}

object Days extends Enumeration {
  type Days = Value
  val Monday = Value
}
```
and the test:
```scala
    val objectMapper = new ObjectMapper()
    objectMapper.registerModule(new DefaultScalaModule)
    val testOne = Test1(Numbers.One, Days.Monday)
    val testTwo = Test2(Some(Numbers.One), Some(Days.Monday))

    val testOneOutput = objectMapper.writeValueAsString(testOne)
    println(testOneOutput)
    val testTwoOutput = objectMapper.writeValueAsString(testTwo)
    println(testTwoOutput)
```
then testOneOutput prints:
```json
{"numbers":"One","days":{"enumClass":"xxx.Days","value":"Monday"}}
```
which is correct since the second enum didn't have the annotation.

testTwoOutput prints:
```json
{"numbers":"One","days":"Monday"}
```
Which is not correct since the second enum didn't have the annotation.

**Comment by ajhcpt** [comment]
And if you try to deserialize back to the object it fails:
```scala
val two = objectMapper.readValue(testTwoOutput, classOf[Test2])
```
Cannot` deserialize instance of `scala.Enumeration$Value` out of VALUE_STRING token
 at [Source: (String)"{"numbers":"One","days":"Monday"}"; line: 1, column: 25] (through reference chain: com.allangray.bpm.jbs.commands.contributions.Test2["days"])
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `scala.Enumeration$Value` out of VALUE_STRING token
 at [Source: (String)"{"numbers":"One","days":"Monday"}"; line: 1, column: 25] (through reference chain: com.allangray.bpm.jbs.commands.contributions.Test2["days"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1092)
	at com.fasterxml.jackson.module.scala.deser.EnumerationDeserializer.deserialize(EnumerationDeserializerModule.scala:32)
	at com.fasterxml.jackson.module.scala.deser.EnumerationDeserializer.deserialize(EnumerationDeserializerModule.scala:29)
	at com.fasterxml.jackson.module.scala.deser.OptionDeserializer.deserialize(OptionDeserializerModule.scala:60)
	at com.fasterxml.jackson.module.scala.deser.OptionDeserializer.deserialize(OptionDeserializerModule.scala:11)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:529)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1280)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)

**Comment by nbauernfeind** [comment]
Very interesting. Thank you for the report and the test case. Which versions of scala and jackson are you using?

**Comment by ajhcpt** [comment]
Good question. This test was executed on Scala 2.12.8 and Jackson 2.9.2. I tried it out on Jackson 2.9.8 and the serialization works as expected. I'm going to close this issue.

**Comment by nbauernfeind** [comment]
Awesome! Thanks for upgrading =). It looks like there was a lot of work done between 2.9.2 and 2.9.4 and this was, likely, inadvertently fixed (because I don't see any commits that explicitly try to fix such a problem). I will turn your use-case into a regression test. Thanks!
