### ISSUE TITLE
Detection of `int` constructor fails for nested constructor case, case class

### ISSUE THREAD

**Issue by xylo** [FasterXML/jackson-module-scala#404]
Here is my scala code:
```scala
case class A(b: B)

class B(id: Int) {
  @JsonIgnore
  def x = id
}

object MyApp {
  def main(args: Array[String]): Unit = {
    val objectMapper = new ObjectMapper()
    objectMapper.registerModule(DefaultScalaModule)

    val a = objectMapper.readValue("""{"b": 1}""", classOf[A])
  }
}
```

I get the following exception when I run this code:
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `B` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (1)
 at [Source: (String)"{"b": 1}"; line: 1, column: 7] (through reference chain: A["b"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1032)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromInt(ValueInstantiator.java:262)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromInt(StdValueInstantiator.java:356)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromNumber(BeanDeserializerBase.java:1324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:173)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at MyApp$.main(MapperTest.scala:17)
	at MyApp.main(MapperTest.scala)
```

However, when `B.x` is defined as `def x = 0` the deserialization works fine.  How is that possible?  Is this a bug in jackson or in jackson-module-scala or did I miss something?

**Comment by nbauernfeind** [comment]
Hmm interesting. Have you already tried this example with B as a java class?

**Comment by xylo** [comment]
Good point.  I will...

**Comment by nbauernfeind** [comment]
I am not sure of the exact reasons why it works if the field is missing or if it is not marked `@JsonIgnore`. However, it does work if you mark the constructor explicitly as a JsonCreator.

```scala
  class B @JsonCreator() (id: Int) {
    @JsonIgnore
    def x = id
  }
```

**Comment by xylo** [comment]
Ah, thanks a lot!  I already tried to do that in Java.  However, in Java it seems to be much more complicated.

**Comment by nbauernfeind** [comment]
Actually... I'm going to leave this open. I think the constructor here should still technically be found automatically.

**Comment by cowtowncoder** [comment]
I am not 100% sure if this is reasonable to expect to work, actually, since what is requested is `A`, and chaining therefore requiring knowledge of nesting to get from `B` to there.
It should work if `@JsonCreator` was marked for `A` constructor, but auto-detection otherwise does not consider Object-valued single-argument constructors.
So this does not seem to be about not finding `int` value constructor (which would be found, but that's for `B`, not `A`) but about nesting/chaining. Maybe it can be supported for case classes (that seems reasonable) but might be tricky.

**Comment by pjfanning** [comment]
I'm closing this - the test case https://github.com/FasterXML/jackson-module-scala/commit/cb535df40ab8ba6555a70b31c144fb8028ad5129 works fine -- the original code is invalid as far as I am concerned - the correct json for the use case is `{"b":{"id":1}}` - `{"b":1}` is not a valid default serialization for this - of course, users can write their own custom serializers/deserializers if they don't like the default serialization
