### ISSUE TITLE
weird new NPE in 2.11.0.rc1

### ISSUE THREAD

**Issue by mosesn** [FasterXML/jackson-module-scala#445]
Hi, while testing 2.11.0.rc1, I saw a strange NPE:

                     java.lang.NullPointerException: null
                      at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:204)
                      at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:204)
                      at scala.collection.SeqLike.size(SeqLike.scala:108)
                      at scala.collection.SeqLike.size$(SeqLike.scala:108)
                      at scala.collection.mutable.ArrayOps$ofRef.size(ArrayOps.scala:198)
                      at scala.collection.IndexedSeqLike.sizeHintIfCheap(IndexedSeqLike.scala:99)
                      at scala.collection.IndexedSeqLike.sizeHintIfCheap$(IndexedSeqLike.scala:99)
                      at scala.collection.mutable.ArrayOps$ofRef.sizeHintIfCheap(ArrayOps.scala:198)
                      at scala.collection.mutable.Builder.sizeHint(Builder.scala:80)
                      at scala.collection.mutable.Builder.sizeHint$(Builder.scala:79)
                      at scala.collection.mutable.ArrayBuilder.sizeHint(ArrayBuilder.scala:25)
                      at scala.collection.TraversableLike.builder$1(TraversableLike.scala:234)
                      at scala.collection.TraversableLike.map(TraversableLike.scala:237)
                      at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
                      at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
                      at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$ScalaValueInstantiator.<init>(ScalaAnnotationIntrospectorModule.scala:129)
                      at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.findValueInstantiator(ScalaAnnotationIntrospectorModule.scala:159)
                      at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:231)
                      at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:220)
                      at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
                      at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
                      at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
                      at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
                      at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
                      at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
                      at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:446)
                      at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:183)
                      at com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$Deserializer.createContextual(GenericFactoryDeserializerResolver.scala:71)
                      at com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$Deserializer.createContextual(GenericFactoryDeserializerResolver.scala:62)
                      at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:684)
                      at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:484)
                      at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4621)
                      at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4400)
                      at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2745)

It looks like it's because of this line:

https://github.com/FasterXML/jackson-module-scala/blob/master/src/main/scala/com/fasterxml/jackson/module/scala/introspect/ScalaAnnotationIntrospectorModule.scala#L128
```
      val args = delegate.getFromObjectArguments(None.orNull)
```
One thing I noticed (which might be unrelated) is that 
None.orNull always returns null, so we can probably replace this with
```
      val args = delegate.getFromObjectArguments(null)
```
for no change.  I'm somewhat stumped what else might be going on here though–I don't think we ever make a custom ValueInstantiator in our codebase, so I don't know how getFromObjectArguments could end up returning null.  Do you have any idea what might be going on?  It does not seem to be an issue in 2.10.3.

**Comment by pjfanning** [comment]
@mosesn thanks for reporting this - can you provide a reproducible test case? If we had your case class(es) it would make life much easier.

This new code was added to support cases class default params - eg `case class Test(p1: String = "default")`

**Comment by pjfanning** [comment]
could you also tell us which version of scala you are using?

**Comment by mosesn** [comment]
We're using scala 2.12.  Let me check if it has default params

**Comment by mosesn** [comment]
Yes, it has many default params, here's an anonymized version:

```
case class UserDetails(
  myId: Long,
  myNum: Long,
  myRatio: Option[Double] = None,
  myOptionalNum: Option[Long] = None,
  fooOptionalNum: Option[Long] = None,
  barOptionalNum: Option[Long] = None,
  quxOptionalNum: Option[Long] = None,
  myOptionalString: Option[String] = None,
  myOptionalString: Option[String],
  fooOptionalString: Option[String] = None,
  barOptionalString: Option[String] = None,
  quxOptionalString: Option[String] = None,
  bazOptionalString: Option[String] = None,
  anotherOptionalString: Option[String] = None,
  andAnotherOptionalString: Option[String] = None,
  yourOptionalString: Option[String] = None,
  yetAnotherOptionalString: Option[String] = None,
  oneMoreOptionalString: Option[String] = None,
  myOptionalStruct1: Option[Struct1] = None,
  myOptionalStruct2: Option[Struct2] = None,
  myBool: Boolean = false,
  myOptionalSeqString: Option[Seq[String]] = None,
  myOptionalStruct3: Option[Struct3] = None,
  myOptionalStruct4: Option[Struct4] = None
)
```

**Comment by pjfanning** [comment]
https://github.com/FasterXML/jackson-module-scala/blob/2.11/src/main/scala/com/fasterxml/jackson/module/scala/introspect/ScalaAnnotationIntrospectorModule.scala#L127 -- you are looking at wrong branch of code - v2.11 is built using branch 2.11

**Comment by pjfanning** [comment]
I'll see if I can reproduce issue with your class

**Comment by mosesn** [comment]
Whoops!  Thanks for clarifying

**Comment by pjfanning** [comment]
I added a couple of simpler test cases - that pass.

Your case class depends on classes called Struct1, Struct2, etc. Can you provide these?

Can you double check that the classes you are providing still cause the problem reported in this issue?

**Comment by mosesn** [comment]
It's very deeply nested.  One interesting thing I noticed was that one of the structs is scrooge-generated: here's an example of what that might look like https://github.com/twitter/scrooge/blob/develop/scrooge-generator-tests/src/test/resources/gold_file_output_scala/com/twitter/scrooge/test/gold/thriftscala/Response.scala#L427-L436 when it's generated.  could that be related?

**Comment by mosesn** [comment]
Just tried running the test again–I can confirm the problem still exists.

**Comment by mosesn** [comment]
After doing more research, I found the problem–there's a class that looks like this:

```
sealed abstract class Struct1(val name: String, val classifier: String = "my_default_string") {
  override def toString: String = name
}
```

when I changed it to:

```
sealed abstract class Struct1(val name: String, val classifier: String) {
  def this(name: String) = this(name, "my_default_string")
  override def toString: String = name
}
```

it no longer throws an NPE

**Comment by mosesn** [comment]
I found a minimal reproduction case:

```
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.{DefaultScalaModule, ScalaObjectMapper}
val mapper = new ObjectMapper with ScalaObjectMapper
abstract class Foo(val bar: String = "foo")
mapper.registerModule(DefaultScalaModule)
mapper.readValue[Foo]("{ \"bar\": \"baz\" }")
```

which results in
```
java.lang.NullPointerException
  at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:204)
  at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:204)
  at scala.collection.SeqLike.size(SeqLike.scala:108)
  at scala.collection.SeqLike.size$(SeqLike.scala:108)
  at scala.collection.mutable.ArrayOps$ofRef.size(ArrayOps.scala:198)
  at scala.collection.IndexedSeqLike.sizeHintIfCheap(IndexedSeqLike.scala:99)
  at scala.collection.IndexedSeqLike.sizeHintIfCheap$(IndexedSeqLike.scala:99)
  at scala.collection.mutable.ArrayOps$ofRef.sizeHintIfCheap(ArrayOps.scala:198)
  at scala.collection.mutable.Builder.sizeHint(Builder.scala:80)
  at scala.collection.mutable.Builder.sizeHint$(Builder.scala:79)
  at scala.collection.mutable.ArrayBuilder.sizeHint(ArrayBuilder.scala:25)
  at scala.collection.TraversableLike.builder$1(TraversableLike.scala:234)
  at scala.collection.TraversableLike.map(TraversableLike.scala:237)
  at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
  at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
  at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$ScalaValueInstantiator.<init>(ScalaAnnotationIntrospectorModule.scala:129)
  at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.findValueInstantiator(ScalaAnnotationIntrospectorModule.scala:159)
  at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:231)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:220)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
  at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
  at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:479)
  at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4621)
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4430)
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
  at com.fasterxml.jackson.module.scala.ScalaObjectMapper.readValue(ScalaObjectMapper.scala:191)
  at com.fasterxml.jackson.module.scala.ScalaObjectMapper.readValue$(ScalaObjectMapper.scala:190)
  at $anon$1.readValue(<console>:15)
  ... 34 elided
```

It seems you need three components: abstract, default arg in constructor, and `val`-ed up constructor arg.

**Comment by pjfanning** [comment]
Thanks. I made a commit to 2.11 code to fix the NullPointerException.
The test case still does not pass - but I get the same error in 2.10 code base.

[info] - should support optional structs with default values *** FAILED ***
[info]   com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.fasterxml.jackson.module.scala.deser.CreatorTest$Struct1` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
[info]  at [Source: (String)"{"s":{"name":"name"}}"; line: 1, column: 6] (through reference chain: com.fasterxml.jackson.module.scala.deser.CreatorTest$ConstructorWithOptionStruct["s"])

Looks like the jackson code does not support abstract classes.

**Comment by mosesn** [comment]
Thanks, I think it will be better as long as it's not a NullPointerException (which I found really tough to debug)

**Comment by mosesn** [comment]
Actually, wait a minute–how come this used to work until 2.11 though? 🤔 shouldn't it still work?

**Comment by pjfanning** [comment]
https://github.com/FasterXML/jackson-module-scala/issues/445#issuecomment-605716341

I get the same error in jackson 2.10 and in 2.11 after my null pointer fix.

**Comment by mosesn** [comment]
OK, makes sense.  Something else must have been going on that it still works for 2.10.3 in my codebase, I'll try again after 2.11.0.rc2 gets published and see if I still need to change the code.

**Comment by mosesn** [comment]
Yeah, it works for me now!  Thanks so much =)
