### ISSUE TITLE
investigate why ConflictingJsonCreator fails with Scala 2.13.6

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#523]
Passes ok with Scala 2.13.5 and only seems to fail with Scala 2.13.6

```
[info] - should support multiple creator annotations with the same parameter names *** FAILED ***
[info]   java.lang.IllegalArgumentException: Cannot construct instance of `com.fasterxml.jackson.module.scala.deser.ConflictingJsonCreator` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (10)
[info]  at [Source: UNKNOWN; byte offset: #UNKNOWN]
[info]   at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4339)
[info]   at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4280)
[info]   at com.fasterxml.jackson.module.scala.deser.CreatorTest.$anonfun$new$14(CreatorTest.scala:186)
[info]   at org.scalatest.FixtureTestSuite$TestFunAndConfigMap.$anonfun$apply$1(FixtureTestSuite.scala:275)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.FixtureTestSuite$TestFunAndConfigMap.apply(FixtureTestSuite.scala:275)
[info]   at com.fasterxml.jackson.module.scala.BaseFixture.withFixture(BaseFixture.scala:15)
[info]   at org.scalatest.flatspec.FixtureAnyFlatSpecLike.invokeWithFixture$1(FixtureAnyFlatSpecLike.scala:2382)
[info]   ...
[info]   Cause: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.fasterxml.jackson.module.scala.deser.ConflictingJsonCreator` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (10)
[info]  at [Source: UNKNOWN; byte offset: #UNKNOWN]
[info]   at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1728)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1353)
[info]   at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromInt(ValueInstantiator.java:324)
[info]   at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromInt(StdValueInstantiator.java:376)
```

**Comment by pjfanning** [comment]
also fails in master branch but with multiple scala versions

**Comment by pjfanning** [comment]
https://github.com/FasterXML/jackson-module-scala/commit/fd6e6a53b8af9a01a390c7767659ee5fc5263969 seems to make the test more robust
