### ISSUE TITLE
ScalaObjectMapper#readValue fails when there's one of the fields is a case class nested in an object in 2.13.0-rc2

### ISSUE THREAD

**Issue by mosesn** [FasterXML/jackson-module-scala#542]
~~I haven't had a chance to try a simple reproduction case in my repl yet, but my suspicion is that this would fail:~~

```
// NOTE: This is actually fine, I was wrong.  I'm leaving the mistaken repro case so the thread makes sense.  See below for the actual repro

object Foo {
  object Bar {
    final case class Baz(num: Int)
  }
}

val mapper: ScalaObjectMapper = 
mapper.readValue[Foo.Bar.Baz]("""{"num": "3"}""")
```

EDIT: Here's an actual repro:

````
scala> :paste
// Entering paste mode (ctrl-D to finish)

import com.fasterxml.jackson.module.scala.ScalaObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import com.fasterxml.jackson.databind.json.JsonMapper
val objectMapper = (JsonMapper.builder().addModule(DefaultScalaModule).build() :: ScalaObjectMapper)
object Foo { case class Bar(num: Int) }
class Baz(baz: Foo.Bar)
objectMapper.readValue[Qux]("""{"baz": {"num": "3"}}""")

// Exiting paste mode, now interpreting.

java.lang.InternalError: Malformed class name
  at java.lang.Class.getSimpleName(Class.java:1330)
  at java.lang.Class.getCanonicalName(Class.java:1399)
  at com.fasterxml.jackson.module.scala.util.TastyUtil$.hasTastyFile(TastyUtil.scala:10)
  at com.fasterxml.jackson.module.scala.util.ClassW.extendsScalaClass(Classes.scala:12)
  at com.fasterxml.jackson.module.scala.util.ClassW.extendsScalaClass$(Classes.scala:9)
  at com.fasterxml.jackson.module.scala.util.ClassW$$anon$1.extendsScalaClass(Classes.scala:34)
  at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.isMaybeScalaBeanType(ScalaAnnotationIntrospectorModule.scala:200)
  at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.isScala(ScalaAnnotationIntrospectorModule.scala:206)
  at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.hasCreatorAnnotation(ScalaAnnotationIntrospectorModule.scala:63)
  at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.findCreatorAnnotation(ScalaAnnotationIntrospectorModule.scala:86)
  at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findCreatorAnnotation(AnnotationIntrospectorPair.java:842)
  at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreatorParam(POJOPropertiesCollector.java:650)
  at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreators(POJOPropertiesCollector.java:617)
  at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:426)
  at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:386)
  at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:233)
  at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
  at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
  at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:328)
  at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:272)
  at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:223)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:261)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:150)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:415)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:350)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
  at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
  at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:642)
  at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4751)
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4621)
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3575)
  at com.fasterxml.jackson.module.scala.ScalaObjectMapper.readValue(ScalaObjectMapper.scala:206)
  at com.fasterxml.jackson.module.scala.ScalaObjectMapper.readValue$(ScalaObjectMapper.scala:205)
  at com.fasterxml.jackson.module.scala.ScalaObjectMapper$Mixin.readValue(ScalaObjectMapper.scala:14)
  ... 42 elided
```

Here's the stack trace I'm seeing:

```
                     java.lang.InternalError: Malformed class name
                     	at java.lang.Class.getSimpleName(Class.java:1330)
                     	at java.lang.Class.getCanonicalName(Class.java:1399)
                     	at com.fasterxml.jackson.module.scala.util.TastyUtil$.hasTastyFile(TastyUtil.scala:10)
                     	at com.fasterxml.jackson.module.scala.util.ClassW.extendsScalaClass(Classes.scala:12)
                     	at com.fasterxml.jackson.module.scala.util.ClassW.extendsScalaClass$(Classes.scala:9)
                     	at com.fasterxml.jackson.module.scala.util.ClassW$$anon$1.extendsScalaClass(Classes.scala:34)
                     	at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$._descriptorFor(ScalaAnnotationIntrospectorModule.scala:157)
                     	at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.fieldName(ScalaAnnotationIntrospectorModule.scala:173)
                     	at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.findImplicitPropertyName(ScalaAnnotationIntrospectorModule.scala:46)
                     	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findImplicitPropertyName(AnnotationIntrospectorPair.java:502)
                     	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:530)
                     	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:421)
                     	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:386)
                     	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:233)
                     	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
                     	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
                     	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:328)
                     	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:272)
                     	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:223)
                     	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:261)
                     	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:150)
                     	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:415)
                     	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:350)
                     	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
                     	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
                     	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
                     	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:632)
                     	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:539)
                     	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
                     	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
                     	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
                     	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:609)
                     	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.createContextual(MapDeserializer.java:316)
                     	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.createContextual(GenericMapFactoryDeserializerResolver.scala:122)
                     	at com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(DeserializationContext.java:825)
                     	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:550)
                     	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:294)
                     	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
                     	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
                     	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:642)
                     	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4751)
                     	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4621)
                     	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3575)
                     	at com.fasterxml.jackson.module.scala.ScalaObjectMapper.readValue(ScalaObjectMapper.scala:206)
                     	at com.fasterxml.jackson.module.scala.ScalaObjectMapper.readValue$(ScalaObjectMapper.scala:205)
```

**Comment by pjfanning** [comment]
ScalaObjectMapper is deprecated - so it is not a high priority for maintenance. If you want to try a fix, please feel free to submit one.

**Comment by pjfanning** [comment]
I just added https://github.com/FasterXML/jackson-module-scala/commit/b75861c7bfa641eb5ccccd209aa0d583451f94db - it passes for me using Scala 2.13.6 and Zulu JDK 11.0.10 - let's see how it fares on the CI/CD build.

**Comment by pjfanning** [comment]
Seems similar to issue in https://github.com/scala/bug/issues/2034 - maybe you could check a newer JDK to see if that helps

**Comment by mosesn** [comment]
OK, I had time to actually sit down with a repl.  It's trickier than I thought–the problem is when the case class is a field.  It also doesn't need to be double nested.

Here's a repro:

```
scala> :paste
// Entering paste mode (ctrl-D to finish)

import com.fasterxml.jackson.module.scala.ScalaObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import com.fasterxml.jackson.databind.json.JsonMapper
val objectMapper = (JsonMapper.builder().addModule(DefaultScalaModule).build() :: ScalaObjectMapper)
object Foo { case class Bar(num: Int) }
class Baz(baz: Foo.Bar)
objectMapper.readValue[Qux]("""{"baz": {"num": "3"}}""")

// Exiting paste mode, now interpreting.

java.lang.InternalError: Malformed class name
  at java.lang.Class.getSimpleName(Class.java:1330)
  at java.lang.Class.getCanonicalName(Class.java:1399)
  at com.fasterxml.jackson.module.scala.util.TastyUtil$.hasTastyFile(TastyUtil.scala:10)
  at com.fasterxml.jackson.module.scala.util.ClassW.extendsScalaClass(Classes.scala:12)
  at com.fasterxml.jackson.module.scala.util.ClassW.extendsScalaClass$(Classes.scala:9)
  at com.fasterxml.jackson.module.scala.util.ClassW$$anon$1.extendsScalaClass(Classes.scala:34)
  at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.isMaybeScalaBeanType(ScalaAnnotationIntrospectorModule.scala:200)
  at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.isScala(ScalaAnnotationIntrospectorModule.scala:206)
  at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.hasCreatorAnnotation(ScalaAnnotationIntrospectorModule.scala:63)
  at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.findCreatorAnnotation(ScalaAnnotationIntrospectorModule.scala:86)
  at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findCreatorAnnotation(AnnotationIntrospectorPair.java:842)
  at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreatorParam(POJOPropertiesCollector.java:650)
  at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreators(POJOPropertiesCollector.java:617)
  at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:426)
  at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:386)
  at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:233)
  at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
  at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
  at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:328)
  at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:272)
  at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:223)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:261)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:150)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:415)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:350)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
  at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
  at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
  at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:642)
  at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4751)
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4621)
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3575)
  at com.fasterxml.jackson.module.scala.ScalaObjectMapper.readValue(ScalaObjectMapper.scala:206)
  at com.fasterxml.jackson.module.scala.ScalaObjectMapper.readValue$(ScalaObjectMapper.scala:205)
  at com.fasterxml.jackson.module.scala.ScalaObjectMapper$Mixin.readValue(ScalaObjectMapper.scala:14)
  ... 42 elided
```

**Comment by mosesn** [comment]
> ScalaObjectMapper is deprecated - so it is not a high priority for maintenance. If you want to try a fix, please feel free to submit one.

I understand, and I'm planning on migrating my company to ClassTagExtensions.  However, we were unable to upgrade to 2.12.x because of a bug, so 2.13.x is our first version that has ClassTagExtensions.  We would rather upgrade the version, and then switch to ClassTagExtensions as a separate commit, so that if we run into issues, we can tell whether they come from ClassTagExtensions.  Would you mind continuing to support ScalaObjectMapper (at least as far as fixing regressions) for scala 2.12.x / 2.13.x for at least a little while until we are able to migrate?

**Comment by mosesn** [comment]
OK, I tried repro-ing in JDK11, you're right that it's fixed if you do that.  However, we will be unable to upgrade to JDK11 anytime soon (it's a work in progress).  Can you use an API that's more JDK8-friendly in the meantime?

**Comment by pjfanning** [comment]
this test passes for me in our CI build on Java 8 - so it could be just a matter of using a more up to data Java 8 install or a different one

**Comment by pjfanning** [comment]
TastyUtil is a new class but Class.getCanonicalName is used in 4 other places in the legacy jackson-module-scala code base - if this was a widespread issue, I would expect there to be lots of people complaining

**Comment by mosesn** [comment]
@pjfanning I was able to get a consistently failing reproduction case.  It seems to fail across 2.11.x, 2.12.x, and 2.13.x.

https://github.com/mosesn/jackson-module-scala/commit/947e7f26c960cadfd66689a8f8f3f2341f9c0d78

**Comment by pjfanning** [comment]
I still can't reproduce this - I've added your Qux test case and it passes - I don't know what to do but I don't think I can spend any more time on this - if you can produce an Github Pull Request, the tests will run on Github Actions CI/CD platform - if there is a test that fails on Github Actions CI/CD platform, I may have time to look at it - but at the moment, this issue is not a priority for me.

**Comment by mosesn** [comment]
Thank you!! I'll try a snapshot build tomorrow.

**Comment by mosesn** [comment]
It worked, thank you again!
