### ISSUE TITLE
Deserialising with generics returns Map

### ISSUE THREAD

**Issue by lambook** [FasterXML/jackson-module-scala#552]
I'm using this Test to deserialize a class with a list of a generic Type T :

```
import _root_.com.fasterxml.jackson.databind.json.JsonMapper
import _root_.com.fasterxml.jackson.databind.{DeserializationFeature, JsonNode, Module, ObjectMapper, SerializationFeature}
import _root_.com.fasterxml.jackson.module.scala.DefaultScalaModule
import _root_.com.fasterxml.jackson.core.util.DefaultIndenter
import _root_.com.fasterxml.jackson.core.util.DefaultPrettyPrinter
import _root_.com.fasterxml.jackson.core.type.TypeReference
import _root_.com.fasterxml.jackson.annotation.JsonSubTypes
import _root_.com.fasterxml.jackson.annotation.JsonSubTypes.Type
import _root_.com.fasterxml.jackson.annotation.JsonTypeInfo
import _root_.com.fasterxml.jackson.annotation.JsonCreator

object TestJson extends App{


  sealed trait Root[T] {
    val value: Any
    val valueSeq: Seq[T]
  }

  object Root {}

 final case class StringChild(override val value: String, 
override val valueSeq: Seq[String]) extends Root[String]

 object StringChild {}
  final case class IntChild(override val value: Int,
                           override val valueSeq: Seq[Int]) extends Root[Int]
  
object IntChild {}
 final case class FloatChild(override val value: Float,
                              override val valueSeq: Seq[Int]) extends Root[Int]

  object FloatChild {}

  object JsonUtils {
    val  mapper  = JsonMapper.builder().addModule(DefaultScalaModule).build()
    mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
   
 def toJson(value: Any): String = {
      mapper.writeValueAsString(value)
    }

    def fromJson[T](json: String): T = {
      val ref =  new TypeReference[T] {}
      mapper.readValue[T](json,ref)
    }
  }


  val sc = StringChild("abc",Seq("efg"))
  val ic = IntChild(value=100, valueSeq=Seq(1,2,3))
  val scjson = JsonUtils.toJson(sc)
 println(JsonUtils.fromJson(scjson).getClass)
 }

´´´


`````````
This gives  : 

```
class scala.collection.immutable.Map$Map2

```

Why? and is there any way to make return the real object : Root

Thank you

**Comment by pjfanning** [comment]
Could you try `val  mapper  = JsonMapper.builder().addModule(DefaultScalaModule).build() :: ClassTagExtensions` (best with jackson-module-scala 2.13.0). This will add a mapper.readValue[T](json: String) - note no TypeReference needed - the type info is derived using a scala.reflect.ClassTag.

**Comment by lambook** [comment]
Thank you @pjfanning

I've tried but not working.

I'm in fact using jackson-module-scala 2.13.0

```
libraryDependencies +="com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.13.0"
```

So changed the code to 

```

 val mapper = JsonMapper.builder().addModule(DefaultScalaModule).build() :: ClassTagExtensions
   
 mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

    def toJson(value: Any): String = {

      mapper.writeValueAsString(value)

    }

    def fromJson[T](json: String): T = {

      mapper.readValue[T](json)   ---> not compiliing

    }
  }

```
* So the method readValue[T](json) is not available even after adding  ClassTagExtensions

And code above at  *  mapper.readValue[T](json)  *   is not compiling and i have this error : 


````
no implicit argument of type com.fasterxml.jackson.module.scala.JavaTypeable[T] 

was found for an implicit parameter of method readValue in trait ClassTagExtensions. I found:  

com.fasterxml.jackson.module.scala.JavaTypeable.gen0JavaTypeable[T]( /* missing */summon[reflect.ClassTag[T]] )  

But no implicit values were found that match type reflect.ClassTag[T]. 

```

Any idea ?

Thank you

**Comment by lambook** [comment]
> Could you try `val mapper = JsonMapper.builder().addModule(DefaultScalaModule).build() :: ClassTagExtensions` (best with jackson-module-scala 2.13.0). This will add a mapper.readValue[T](json: String) - note no TypeReference needed - the type info is derived using a scala.reflect.ClassTag.

Thank you @pjfanning

I've tried but not working.

I'm in fact using jackson-module-scala 2.13.0

libraryDependencies +="com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.13.0"
So changed the code to


 val mapper = JsonMapper.builder().addModule(DefaultScalaModule).build() :: ClassTagExtensions
   
 mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

    def toJson(value: Any): String = {

      mapper.writeValueAsString(value)

    }

    def fromJson[T](json: String): T = {

      mapper.readValue[T](json)   ---> not compiliing

    }
  }

So the method readValueT is not available even after adding ClassTagExtensions
And code above at * mapper.readValueT * is not compiling and i have this error :

no implicit argument of type com.fasterxml.jackson.module.scala.JavaTypeable[T] 

was found for an implicit parameter of method readValue in trait ClassTagExtensions. I found:  

com.fasterxml.jackson.module.scala.JavaTypeable.gen0JavaTypeable[T]( /* missing */summon[reflect.ClassTag[T]] )  

But no implicit values were found that match type reflect.ClassTag[T]. 

```

Any idea ?

Thank you

**Comment by pjfanning** [comment]
If you insist on keeping your own fromJson def instead of using the mapper.readValue directly, you will need something like.

```
    def fromJson[T: JavaTypeable](json: String): T = {
      mapper.readValue[T](json)   ---> not compiliing
    }
```

**Comment by lambook** [comment]
> def fromJson[T: JavaTypeable](json: String): T = {
>       mapper.readValue[T](json) 
>     }

Thank you so much

But it s still not working 


```


    def fromJson[T: JavaTypeable](json: String): T = {
      mapper.readValue[T](json)
    }

  }



 val sc = StringChild("abc",Seq("efg"))

 val scjson = JsonUtils.toJson(sc)

 println(JsonUtils.fromJson(scjson).getClass)


```

** gives me

```
class scala.collection.immutable.Map$Map2

```

and not the real Object ....

**Comment by pjfanning** [comment]
this works for me - https://scastie.scala-lang.org/pjfanning/zlNgUcq0SVSwNtpISWeNqg/3

**Comment by lambook** [comment]
> this works for me - https://scastie.scala-lang.org/pjfanning/zlNgUcq0SVSwNtpISWeNqg/3

Yes that work that way.

But 

Lets say i have A generic parametrised class like this 

Test[T] (Id:Int, Seq[T]))


And somewhere in my code i don t know yet the type of T 

```
private def get[T](str:String): T = {

---I have to deserialize some this into Test[T] here and then process it into T


}

```
How can i call it in this case ? 

all these : 

```
JsonUtils.fromJson[Test](str) 

JsonUtils.fromJson[Test[T]](str) 

````

***  give me error

```
no implicit argument of type com.fasterxml.jackson.module.scala.JavaTypeable[T] was found for an implicit parameter of method fromJson in class JsonConverter. I found:  com.fasterxml.jackson.module.scala.JavaTypeable.gen0JavaTypeable[T]( /* missing */summon[reflect.ClassTag[T]] ) 
```

**Comment by pjfanning** [comment]
Everything that calls fromJson needs to know the fully formed type or it will not work. Ultimately, the serialization code is not magic - you need to tell you what type to deserialize to.

**Comment by pjfanning** [comment]
If you need to deserialize json with different reference types (say `T`), eg MyClass[Int], MyClass[String] - you will need to have some context available somewhere to let you know what the T is. You could put it in the JSON as a separate field. 

Jackson has a Java annotation - JsonTypeInfo - that can be used for this - or you could do some kind of custom solution.

**Comment by lambook** [comment]
> If you need to deserialize json with different reference types (say `T`), eg MyClass[Int], MyClass[String] - you will need to have some context available somewhere to let you know what the T is. You could put it in the JSON as a separate field.
> 
> Jackson has a Java annotation - JsonTypeInfo - that can be used for this - or you could do some kind of custom solution.

Thank you 

I added annotations etc 

and now i'm struggling with this error : 

```

Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.sample.TestJson.main(TestJson.scala)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"{"value":"abc","valueSeq":["efg"]}"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1420)
	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:932)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3630)
	at com.fasterxml.jackson.module.scala.ClassTagExtensions.readValue(ClassTagExtensions.scala:135)
	at com.fasterxml.jackson.module.scala.ClassTagExtensions.readValue$(ClassTagExtensions.scala:22)

```



* The code : 


```
mport _root_.com.fasterxml.jackson.databind.json.JsonMapper
import _root_.com.fasterxml.jackson.databind.{DeserializationFeature, JsonNode, Module, ObjectMapper, SerializationFeature}
import _root_.com.fasterxml.jackson.module.scala.DefaultScalaModule
import _root_.com.fasterxml.jackson.module.scala.ClassTagExtensions
import _root_.com.fasterxml.jackson.module.scala.JavaTypeable
import _root_.com.fasterxml.jackson.core.util.DefaultIndenter
import _root_.com.fasterxml.jackson.core.util.DefaultPrettyPrinter
import _root_.com.fasterxml.jackson.core.`type`.TypeReference
import _root_.com.fasterxml.jackson.annotation.JsonSubTypes
import _root_.com.fasterxml.jackson.annotation.JsonSubTypes.Type
import _root_.com.fasterxml.jackson.annotation.JsonTypeInfo
import _root_.com.fasterxml.jackson.annotation.JsonTypeInfo.Id
import _root_.com.fasterxml.jackson.annotation.JsonCreator
import _root_.com.fasterxml.jackson.annotation.JsonProperty
import _root_.com.fasterxml.jackson.annotation.JsonTypeName

import _root_.com.fasterxml.jackson.databind.annotation.JsonDeserialize


import scala.collection.immutable.Map.Map3
import scala.reflect.ClassTag
object TestJson extends App{


  @JsonTypeInfo(use = Id.NAME,
    include = JsonTypeInfo.As.PROPERTY, property = "type")
  @JsonSubTypes(Array(
  new Type(value = classOf[IntChild], name="int"),
  new Type(value = classOf[StringChild], name="string"),
  new Type(value = classOf[FloatChild], name="float")
  ))
  sealed trait Root[T] {
    @JsonProperty("value")
    val value: Any
    @JsonProperty("valueSeq")
    val valueSeq: Seq[T]
  }


  @JsonTypeName("string")
  final case class StringChild(override val value: String,
                               @JsonDeserialize(contentAs = classOf[java.lang.String])
                               override val valueSeq: Seq[String]) extends Root[String]

  @JsonTypeName("int")
  final case class IntChild(override val value: Int,
                            override val valueSeq: Seq[Int]) extends Root[Int]

  final case class FloatChild(override val value: Float,
                              override val valueSeq: Seq[Int]) extends Root[Int]

  object JsonUtils {

    val mapper = JsonMapper.builder().addModule(DefaultScalaModule).build() :: ClassTagExtensions
    mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
    def toJson(value: Any): String = {
      mapper.writeValueAsString(value)
    }

    def fromJson[T: ClassTag](json: String): T = {
      mapper.readValue[T](json)
    }

  }

 // i need to return Root[T] here and not with a specific type
  def testGeneric[T: ClassTag] (): Root[T] ={

    val sr : String = """{"value":"abc","valueSeq":["efg"]}"""
    println("blabla "+JsonUtils.fromJson[T](sr))
    JsonUtils.fromJson[Root[T]](sr)
  }

  //call
  testGeneric[String]()

 }



```

any idea : 


Thnx
