### ISSUE TITLE
scala.math.BigInt support breaks when fast number parsing features are enabled

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#616]
It works ok with vanilla JsonMapper/ObjectMapper setups.

```
    val mapper = JsonMapper.builder()
      .enable(StreamReadFeature.USE_FAST_DOUBLE_PARSER)
      .enable(StreamReadFeature.USE_FAST_BIG_NUMBER_PARSER)
      .build()
    Seq("1.0E2", "1.0e2", "1.0e2", "10000E-2").foreach { numString =>
      mapper.readValue(numString, classOf[BigInt]) shouldBe BigDecimal(numString).toBigIntExact.orNull
    }
```

fails with:
```
[info]   com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `scala.math.BigInt` (no Creators, like default constructor, exist): no double/Double-argument constructor/factory method to deserialize from Number value (100.0)
[info]  at [Source: (String)"1.0E2"; line: 1, column: 1]
[info]   at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1909)
[info]   at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:408)
[info]   at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1354)
[info]   at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromDouble(ValueInstantiator.java:357)
[info]   at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromDouble(StdValueInstantiator.java:457)
[info]   at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromDouble(BeanDeserializerBase.java:1527)
[info]   at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:201)
[info]   at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
[info]   at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
[info]   ...
```

**Comment by pjfanning** [comment]
Of course, the issue was that I didn't add the DefaultScalaModule.
