### ISSUE TITLE
native image support

### ISSUE THREAD

**Issue by chenkovsky** [FasterXML/jackson-module-scala#621]
it seems that native image is not supported currently.

```
Caused by: java.util.NoSuchElementException: key not found: groupId
	at scala.collection.MapOps.default(Map.scala:274)
	at scala.collection.MapOps.default$(Map.scala:273)
	at scala.collection.AbstractMap.default(Map.scala:405)
	at scala.collection.MapOps.apply(Map.scala:176)
	at scala.collection.MapOps.apply$(Map.scala:175)
	at scala.collection.AbstractMap.apply(Map.scala:405)
	at com.fasterxml.jackson.module.scala.JacksonModule$.version$lzycompute(JacksonModule.scala:27)
	at com.fasterxml.jackson.module.scala.JacksonModule$.version(JacksonModule.scala:26)
	at com.fasterxml.jackson.module.scala.JacksonModule.version(JacksonModule.scala:44)
	at com.fasterxml.jackson.module.scala.JacksonModule.version$(JacksonModule.scala:44)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.version(DefaultScalaModule.scala:17)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:826)
	at com.fasterxml.jackson.databind.cfg.MapperBuilder.addModule(MapperBuilder.java:327)
```

**Comment by pjfanning** [comment]
I'm afraid that 'native image' is ambiguous. Could you provide a few line description of what you are doing? You should always do this - you can't assume that a 1 line description will be understood. Are you talking about scala-native, graalVM, maybe something esle?

The code that is failing is trying to read a file from the classpath - called com/fasterxml/jackson/module/scala/build.properties

That file should contain something like:
```
version=2.15.0-SNAPSHOT
groupId=com.fasterxml.jackson.module
artifactId=jackson-module-scala
```

The version number can differ depending on which jackson-module-scala you are using. The other 2 properties should be the same as the example above.

Maybe the tool that is generating the native image is loosing

**Comment by chenkovsky** [comment]
it’s graalvm. Native image is built successfully. Exception is thrown in runtime

**Comment by chenkovsky** [comment]
for attached isssue. it's simple to solve.
add file resources/META-INF/native-image/com.fasterxml.jackson.module/jackson-module-scala/resource-config.json
```
{
  "resources": [{
    "pattern": "com/fasterxml/jackson/module/scala/build.properties"
  }]
}
```
but it seems deserialization still doesnt work, it complains no default constructor for case class with default arguments in runtime. I have to debug it.

**Comment by pjfanning** [comment]
I presume you mean that anyone who is building a GraalVM native image can add that resource-config.json to their own build. I have no plans to add such a file to jackson-module-scala. I would be worried that different native image frameworks would have different standards.

**Comment by chenkovsky** [comment]
yes. user can add this file by theirselves.

**Comment by cowtowncoder** [comment]
@chenkovsky I think for Graal there is an annotation to use to mark classes for which reflection should be available; you may need to add that to value classes?
(I remember this wrt Quarkus)

**Comment by chenkovsky** [comment]
@cowtowncoder  thank you for your suggestion.

first. I added a file META-INF/native-image/reflect-config.json
```json
[{
  "name" : "Mycaseclass",
  "allDeclaredConstructors" : true,
  "allPublicConstructors" : true,
  "allDeclaredMethods" : true,
  "allPublicMethods" : true,
  "allDeclaredFields" : true,
  "allPublicFields" : true
}]
```
but no luck.

then I also modified class definition.
```scala
// original definition is: case class Mycaseclass(val param1: String = "")
case class Mycaseclass(val param1: String) {
    def this() {
        this("")
    }
}
```

it works. it's so tricky.
