### ISSUE TITLE
investigate deserialization case that works in Jackson 2.18 but fails in Jackson 3

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-module-scala#682]
https://github.com/FasterXML/jackson-module-scala/commit/20328f7f9a4305f742a1fb7e6c4c003a47cca18c

```
[info] - should use secondary constructor annotated with JsonCreator (Case Class) *** FAILED ***
[info]   tools.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized property "dummy" (class tools.jackson.module.scala.deser.CreatorTest$CaseClassAlternativeConstructor), not marked as ignorable (one known property: "script"])
[info]  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); byte offset: #UNKNOWN] (through reference chain: tools.jackson.module.scala.deser.CreatorTest$CaseClassAlternativeConstructor["dummy"])
[info]   at tools.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
[info]   at tools.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1208)
[info]   at tools.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1947
[info]   at tools.jackson.databind.deser.bean.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1726)
[info]   at tools.jackson.databind.deser.bean.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1704)
[info]   at tools.jackson.databind.deser.bean.BeanDeserializer._vanillaDeserializeWithUnknown(BeanDeserializer.java:433)
[info]   at tools.jackson.databind.deser.bean.BeanDeserializer.deserialize(BeanDeserializer.java:297)
[info]   at tools.jackson.databind.deser.bean.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:619)
[info]   at tools.jackson.databind.deser.bean.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1419)
[info]   at tools.jackson.databind.deser.bean.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:483)
[info]   ...
```

**Comment by pjfanning** [comment]
This test is passing now but it does behave differently to Jackson 2.18. I think the Jackson 3 behaviour is more correct.
https://github.com/FasterXML/jackson-module-scala/commit/cb496ae9fbdf6c5c44b93825378b48d49011b91b
